<?php 
	$selected 	= "asie";
	$title 		= "World Press Freedom Index 2014 | ASIA"
?>
<?php include "en-header.php" ?>
<h2><b>Asia-Pacific</b></h2>
<h5>CHINESE BIG BROTHER IS WATCHING, AND EXPORTING ITS METHODS</h5>
In a speech shortly after his appointment as Communist Party general secretary in November 2012, Xi Jinping addressed journalists directly: “Friends from the press, China needs to learn more about the world, and the world also needs to learn more about China. I hope you will continue to make more efforts and contributions to deepening the mutual understanding between China and the countries of the world."

Woe to any journalist who thought he was saying “Describe China’s stark realities” when what he really meant was “Follow the Party’s propaganda to the letter!” Since the speech, the authorities have arrested more journalists and bloggers, cracked down harder on cyber-dissidents, reinforced online content control and censorship and stepped up restrictions on the <a href="http://en.rsf.org/chine-new-york-times-reporter-has-to-03-01-2013,43853.html">foreign media</a>.

Embarrassing officials or exposing corruption means risking public condemnation. <strong>Luo Changping</strong>, a journalist who was forced to leave <i>Caijing</i> magazine in November, <strong><a href="http://en.rsf.org/chine-detained-investigative-journalist-11-10-2013,45321.html">Liu Hu</a></strong>, a <i>New Express</i> reporter who was arrested for disseminating “false information”, and the <a href="http://en.rsf.org/china-new-york-times-hounded-by-chinese-05-02-2013,44021.html"><i>New York Times</i></a> newspaper are among the recent examples of journalists and news media that have been punished for investigative reporting. Human rights activists and dissident bloggers such as <strong><a href="http://en.rsf.org/china-four-years-in-prison-for-cyber-28-01-2014,45789.html">Xu Zhiyong</a></strong> and <strong>Yang Maodong</strong> (also known as Guo Feixiong), who were jailed on trumped-up charges are among those who paid a high price in the past year.

The daily “directives” to the traditional media from the Department of Propaganda, the constant <a href="http://en.rsf.org/chine-news-providers-targeted-by-anti-03-10-2013,45286.html">online censorship</a>, the growing number of arbitrary arrests and the detention of the largest number of journalists and netizens in the world (including 2010 Nobel peace laureate <strong><a href="http://en.rsf.org/chine-don-t-forget-liu-xiaobo-held-for-24-12-2013,45670.html">Liu Xiaobo</a></strong>) have made China a model of censorship and repression. Adoption of the model is unfortunately spreading in the region.

Vietnam has stepped by information control to the point of being close to catching up with its Chinese big brother. Independent news providers are subject to enhanced Internet surveillance, draconian directives, <a href="http://en.rsf.org/vietnam-blogger-and-former-party-official-17-06-2013,44801.html">waves of arrests</a> and <a href="http://en.rsf.org/vietnam-defence-rights-violated-at-two-16-08-2013,45060.html">sham trials</a>. Vietnam continues to be the world’s second largest prison for bloggers and netizens. Of the 34 bloggers currently detained, 25 were arrested since Nguyen Phu Trong became the party’s general secretary in January 2011.

The party took censorship to a new level in September 2013 when it issued <a href="http://en.rsf.org/vietnam-government-wants-to-ban-internet-02-08-2013,45008.html">Decree 72</a> banning the use of blogs and social networks to share information about news developments. It shows that the party is waging an all-out offensive against the new-generation Internet, which it sees as a dangerous counterweight to the domesticated traditional media.
<h5>ASIAN AND PACIFIC DEMOCRACIES</h5>
<div>

The past year showed that certain governments in the Asia-Pacific region, even democratic ones, can be extremely sensitive to criticism. This was evident from the many judicial proceedings, often resulting in disproportionate sentences, that were initiated against journalists under pressure from government agencies or officials.

The Thai government uses lèse-majesté charges as an effective weapon for intimidating or silencing those who are disrespectful. The suspended jail sentence imposed on <a href="http://en.rsf.org/thailande-appeal-court-upholds-website-07-11-2013,45439.html"><strong>Chiranuch Premchaiporn</strong></a> (also known as <strong>Jiew</strong>), the editor of the online newspaper <i>Prachatai</i>, for “comments critical of the monarchy” and the 11-year-jail sentence given to <a href="http://en.rsf.org/thailand-editor-gets-11-year-jail-term-in-23-01-2013,43936.html"><strong>Somyot Prueksakasemsuk</strong></a>, editor of the <i>Voice of Thaksin</i> bimonthly, were noteworthy examples. These sentences had a deterrent effect on the entire Thai media.

In South Korea, independent journalists <strong>Kim Ou-joon</strong> and <strong>Choo Chin-woo</strong> were accused of broadcasting “false information” and “defamatory content” about President Park Geun-hye’s brother and father in their satirical podcast “Naneun Ggomsuda.” In Tonga and Papua New Guinea, four journalists were <a href="http://en.rsf.org/papua-new-guinea-three-tv-journalists-sidelined-for-08-11-2013,45441.html">fined or sanctioned</a> for “criticizing” their respective prime ministers.

The Asian democracies also have “forbidden areas” where news is subject to blackouts or censorship. In northern India’s Kashmir region and in Indonesia’s West Papua province, the work of journalists is handicapped by draconian news control policies. In Kashmir, the authorities impose <a href="http://en.rsf.org/india-news-media-and-internet-totally-13-02-2013,44066.html">curfews</a> and often <a href="http://en.rsf.org/india-news-media-and-internet-totally-13-02-2013,44066.html">block the Internet</a> and mobile phone networks.
<h6>Surveillance and confidentiality of sources</h6>
In Australia, the lack of adequate legislative protection for the confidentiality of journalists’ sources continues to expose them to the threat of imprisonment for contempt of court for refusing to reveal their sources. No fewer than seven requests for disclosure of sources were submitted to the courts in 2013 alone. In New Zealand, the interception of reporter <strong>Jon Stephenson</strong>’s metadata by the military, which thought his articles were overly critical, and the release of journalist <strong>Andrea Vance</strong>’s phone records to a leak investigation is indicative of growing government mistrust of the media and their watchdog role.
<h6>Chinese threat</h6>
China’s growing economic weight is allowing it to extend its influence over the media in Hong Kong, Macau and Taiwan, which had been largely spared political censorship until recently. Media independence is now in jeopardy in these three territories, which are either “special administrative regions” or claimed by Beijing. The Chinese Communist Party’s growing subjugation of the Hong Kong executive and its pressure on the Hong Kong media through its “Liaison Office” is increasingly compromising media pluralism there. It has also been threatened in Taiwan by the pro-Beijing Want Want group’s acquisition of the <i>China Times</i>.
<div class="encadre">
<h6><b>Censorship of Fukushima</b></h6>
Arrests, home searches, interrogation by the domestic intelligence agency and threats of judicial proceedings – who would have thought that covering the aftermath of the 2011 Fukushima nuclear disaster would have involved so many risks for <a href="http://en.rsf.org/japan-freelance-journalists-face-23-05-2012,42669.html">Japan’s freelance journalists</a>? The discrimination <a href="http://en.rsf.org/japon-nuclear-industry-entrepreneur-10-07-2012,42991.html">against freelance</a> and foreign reporters resulting from Japan’s unique system of Kisha clubs, whose members are the only journalists to be granted government accreditation, has increased since Fukushima.

Often <a href="http://en.rsf.org/japon-journalists-barred-from-anti-06-11-2012,43640.html">barred</a> from press conferences given by the government and TEPCO (the Fukushima nuclear plant’s owner), denied access to the information available to the mainstream media (which censor themselves), freelancers have their hands tied in their fight to cover Japan’s nuclear industrial complex, known as the “nuclear village.” Now that Prime Minister Shinzo Abe’s government has tightened the legislation on <a href="http://en.rsf.org/japan-prime-minister-shinzo-abe-urged-to-27-11-2013,45515.html">“state secrets,”</a> their fight will get even more dangerous.

</div>
</div>
<h5></h5>
<h5>VIOLENCE AND IMPUNITY IN INDIAN SUB-CONTINENT</h5>
<div>

For the second year running, the Indian sub-continent is the Asian region with the biggest rise in violence for journalists. The most disturbing development is the increasingly targeted nature of the violence. In Nepal, Maoist party activists were more <a href="http://en.rsf.org/nepal-twenty-two-journalists-flee-25-01-2013,43956.html">aggressive towards journalists</a> who criticize their leaders, especially in the run-up to constituent assembly elections in November.

A record number of <a href="http://en.rsf.org/india-three-newspaper-employees-murdered-22-05-2013,44652.html">eight journalists</a> and one media worker were killed in India in 2013. Half of these deaths were premeditated reprisals. This was twice the 2012 death toll and more than the death toll in Pakistan, long the world’s deadliest country for media personnel. Criminal organizations, <a href="http://en.rsf.org/inde-police-target-journalists-covering-27-12-2012,43842.html">security forces</a>, <a href="http://en.rsf.org/nepal-proposed-new-constitution-fuels-22-05-2012,42657.html">demonstrators</a> and armed groups all pose a threat to India’s journalists. The violence and the resulting self-censorship is encouraged by the lack of effective investigations by local authorities, who are often quick to abandon them, and inaction on the part of the federal authorities.

It was a grim year for freedom of information in Bangladesh as well. Independent <a href="http://en.rsf.org/bangladesh-blogger-freed-on-bail-but-still-28-06-2013,44876.html">bloggers</a>, especially those covering the trials of former political leaders accused of war crimes during the 1971 independence war, have been the targets of constant physical attacks since February. One, <strong>Ahmed Rajib Haider</strong>, was hacked to death. Another, <strong>Asif Mohiuddin</strong>, was <a href="http://en.rsf.org/bangladesh-blogger-badly-wounded-in-dhaka-16-01-2013,43916.html">stabbed</a> by Islamist activists who accused him of blasphemy and insulting the Prophet. Journalists were <a href="http://en.rsf.org/bangladesh-reporters-attacked-by-rioting-07-05-2013,44579.html">targeted</a> by both police and rioting protesters during a series of demonstrations from May to October to demand a blasphemy law. The February 2012 murders of journalists <a href="http://en.rsf.org/bangladesh-international-investigation-11-02-2013,44060.html"><strong>Sagar Sarowar</strong> and <strong>Meherun Runi</strong></a> are still unpunished.

The same lack of interest in rendering justice is to be found in Pakistan, where the government seems powerless against not only the Taliban, Jihadis and other armed groups but also the military apparatus, which international observers describe as a “state within the state.” <a href="http://en.rsf.org/pakistan-balochi-journalist-s-mutilated-22-08-2013,45095.html">Seven</a> journalists were murdered in connection with their work in 2013. <a href="http://en.rsf.org/pakistan-three-journalists-killed-three-12-01-2013,43905.html">Four of them</a> – <strong>Mohammad Iqbal</strong> of <i>News Network International</i>, <strong>Saifur Rehman</strong> and <strong>Imran Shaikh</strong> of <i>Samaa News</i> and <a href="http://en.rsf.org/pakistan-another-journalist-gunned-down-01-03-2013,44159.html"><strong>Mehmood Ahmed Afridi</strong></a> – were killed in Balochistan, Pakistan’s deadliest province.

While armed groups pose the biggest threat to Pakistani journalists, the intelligence agencies, especially Inter-Services Intelligence (ISI), continue to represent a danger. Journalists who dare to speak out accuse the military of spying on media personnel, <a href="http://en.rsf.org/pakistan-reporter-held-incommunicado-by-18-10-2013,45345.html">abducting</a> them, torturing them and even murdering them.

</div>
<div class="encadre">
<h6><i>Uthaya</i><i>n</i>:  <b>for some media, the war is far from over</b></h6>
Northern Sri Lanka’s Tamil-language daily <i>Uthayan</i> was the target of <a href="http://en.rsf.org/sri-lanka-second-armed-attack-on-tamil-15-04-2013,44377.html">two violent attacks</a> within the space of 10 days in April. Two of its employees were nearly killed, its printing press was set on fire and its premises were badly damaged. These raids could not however be blamed on the civil war between the Tamil Tigers and the regular army because that officially ended in May 2009.

Founded in 1985, <i>Uthayan</i> was the only Tamil newspaper not to suspend publishing at any time during the civil war. Today it is read by nearly 100,000 Tamils, or 20 per cent of the population of the Jaffna Peninsula. It does hesitate to criticize the ruling Rajapaksa family’s authoritarian methods and continues to pay a high price for not kowtowing to either the military or the government. Six of its employees have been killed in connection with their work. In December 2013, <i>Uthayan</i> received the <a href="http://en.rsf.org/sri-lanka-press-freedom-prize-goes-to-uzbek-27-11-2013,45522.html">Reporters Without Borders Press Freedom Prize</a>.

&nbsp;

</div>
<h5>BURMA’S DEMOCRATIC SPRING STARTS TO FALTER</h5>
Are Burma’s reforms and democratization beginning <a href="http://en.rsf.org/birmanie-will-media-freedom-continue-to-13-03-2012,42104.html">to run out of steam</a>? More and more international human rights NGOs are beginning to worry, and rightly so. The widespread euphoria generated by the successive amnesties of political prisoners in October 2011 and January 2012 has evaporated. The government is struggling to resolve sectarian and ethnic conflicts. With more freedom to speak out, civil society is complaining about the authorities.

The launch of privately-owned daily newspapers was one of the big novelties of 2013. The government announced in March that it had given permission for eight dailies and was studying permit requests for at least six other publications including some operated by former “exile media” that have returned to Burma and set up shop in Rangoon. A score of these new newspapers are already being sold on the streets of the main cities. The transformation of the media landscape also includes the creation of several online media and radio stations.

The process has been accelerated by the assistance provided by international organizations that promote and defend the media. These initiatives have included training in media technology and professional ethics. They have also benefited Burma’s minorities, some of which now have local media in their own language.

The legislative framework has evolved more slowly. The government and parliament kept the promises made in 2012 to end prior censorship and grant more freedom to the media and media organizations. But the promise to draft media legislation that complies with international standards <a href="http://en.rsf.org/burma-upper-house-most-not-approve-09-07-2013,44916.html">has not been kept</a>. Without any consultation, the government submitted a draft media law to the lower house of the parliament (the Pyidaungsu Hluttaw) on 4 March that would impose clearly <a href="http://en.rsf.org/burma-retrograde-bill-threatens-07-03-2013,44176.html">unacceptable restrictions</a> on media freedom. The printing and publications law and the latest draft of a proposed broadcast media law also reveal government ambivalence about real respect for fundamental rights.

The reform process is nonetheless being watched with great interest elsewhere, especially in neighbouring countries such as Laos, where the situation of freedom of information has stagnated alarmingly, in Cambodia, in <a href="http://en.rsf.org/singapore-government-subjects-news-websites-30-05-2013,44689.html">Singapore</a>, where the authorities are on edge, and in <a href="http://en.rsf.org/vietnam-programmed-death-of-freedom-of-23-09-2013,45222.html">Vietnam</a>, still in the grip of authoritarian single-party rule. The governments and population of these countries are following the development of a new regional model of governance in Burma, a model that is still far from proving itself. Will Burma become Southeast Asia’s benchmark for positive change in freedom of information? This remains to be seen.

<?php include "en-footer.php" ?>