<?php 
	$selected 	= "ameriques";
	$title 		= "World Press Freedom Index 2014 | AMERICAS"
?>
<?php include "en-header.php" ?>
<h2>Americas</h2>
<h5>MEDIA UNDER THREAT FROM VIOLENCE</h5>
<p>
More than 20 years have passed since the military dictatorships and civil wars ended in Latin America and the Caribbean, except <a href="http://en.rsf.org/colombia.html">Colombia</a>, which still endures an armed conflict that began half a century ago. <a href="http://en.rsf.org/cuba.html">Cuba</a> is also distinguished by a regime inherited from the Cold War that tolerates no independent watchdogs although an emerging civil society is challenging its “model.”
</p><p>
Peace and democratic institutions have been established in the region, at least formally, as there is a long road from constitutional guarantees of civil liberties to real democracy with respect for the rule of law. Many journalists and human rights defenders continue to be exposed to a high level violence that comes from different quarters including organized crime, paramilitary groups and sometimes the state.
</p><p>
<a href="http://en.rsf.org/honduras.html">Honduras</a> is an example of such a confluence of violence, with a murder rate comparable to that of a country at war – 80 per 100,000 in a population of 7 million. More than 30 journalists have been killed in the past decade, 27 of them since the <a href="http://en.rsf.org/honduras-media-in-coup-storm-07-09-2009,33697.html">June 2009 coup</a> that ousted Manuel Zelaya, an elected president. A link with the victim’s work as a journalist has been established in nine of these murders but almost all of them have gone unpunished in this failed state. Militias in the pay of big landowners, the militarized police, the army and the criminal cartels all have a hand in the threats, beatings and shootings and in the “protection” of certain media.
</p><p>
The situation is similar in other parts of Central America and the Andes. In <a href="http://en.rsf.org/peru.html">Peru</a> and Colombia, covering drug trafficking, corruption, land conflicts or mining conflicts exposes journalists to reprisals. There is a slim but real hope of an imminent peace accord between the Colombian government and the guerrillas of the Revolutionary Armed Forces of Colombia (FARC). Nonetheless, even if the hope is realized, it will leave the narco-paramilitaries, a side-product of the civil war, still in place. How many journalists, trade unions, human rights lawyers and civil society activists have been subjected to often deadly harassment and pressure from reconstituted paramilitary units such as the <a href="http://en.rsf.org/spip.php?page=predateur&amp;id_article=44493">Urabeños or Rastrojos</a>?
</p><p>
In <a href="http://en.rsf.org/mexico.html">Mexico</a>, the <a href="http://en.rsf.org/predator-mexico-miguel-trevino-morales-alias-z-40-and-the-zetas-drug-cartel,44502.html">Zetas</a> and other criminal organizations act in a similar predatory manner towards journalists with the complicity of corrupt local, and sometimes federal, officials. No fewer than 88 journalists were killed from 2000 to the end of 2013, and 18 others disappeared during the same period. This appalling death toll was aggravated by the so-called “federal offensive” against the drug cartels under President Felipe Calderón (2006-2012), in which more than 60,000 people were killed.
</p><p>
Organized crime and its infiltration of the state apparatus also obstructs media work and, in particular, investigative reporting in countries further south such as <a href="http://en.rsf.org/brazil.html">Brazil</a> and <a href="http://en.rsf.org/paraguay.html">Paraguay</a>. In these countries, and in others, the position of journalists is often weakened by their lack of status, a lack of solidarity within the profession and the tragic subjugation of the media, especially the regional media, to centres of political power and influence. In Brazil, the <a href="http://en.rsf.org/bresil-thirty-berlusconis-south-american-24-01-2013,43938.html">phenomenon of “colonels,”</a> regional politicians who are also businessmen and media owners, constitutes a major obstacle to media pluralism and independence, turning journalists into the tools of local barons and exposing them to often deadly score-settling.
</p><p>
Journalists and news media are also political tools in highly polarized countries where the polarization between the private sector and the public sector (or the state) develops into sometimes violent confrontation. An extreme example is <a href="http://en.rsf.org/venezuela.html">Venezuela</a>, where the level of insults and physical attacks increases during the frequent election campaigns. A similar climate exists in <a href="http://en.rsf.org/ecuador.html">Ecuador</a> and <a href="http://en.rsf.org/bolivia.html">Bolivia</a> and, to a lesser extent, <a href="http://en.rsf.org/argentina.html">Argentina</a>.
</p>
&nbsp;
<h5>USA AND BRAZIL – NEW WORLD GIANTS THAT SET A BAD EXAMPLE</h5>
<p>
One is a superpower and the other an emerging power. One for a long time was the embodiment of an established democracy where civil liberties reign supreme. The other created the conditions for developing a powerful civil society during the Lula years (2003-2010) on the basis of a democratic constitution adopted just three years after the end of two decades of military dictatorship (1964-1985). Rich in diversity, the <a href="http://en.rsf.org/united-states.html">United States</a> and Brazil should have given freedom of information a supreme position both in their laws and their social values. Unfortunately the reality falls far short of this.
</p><p>
In the United States, 9/11 spawned a major conflict between the imperatives of national security and the principles of the constitution’s First Amendment. This amendment enshrines every person’s right to inform and be informed. But the heritage of the 1776 constitution was shaken to its foundations during George W. Bush’s two terms as president by the way journalists were harassed and even imprisoned for refusing to reveal their sources or surrender their files to federal judicial officials.
</p><p>
There has been little improvement in practice under Barack Obama. Rather than pursuing journalists, the emphasis has been on going after their sources, but often using the journalist to identify them. No fewer that eight individuals have been charged under the <a href="http://en.rsf.org/united-states-freedom-of-information-threatened-22-05-2013,44651.html">Espionage Act</a> since Obama became president, compared with three during Bush’s two terms. While 2012 was in part the year of <em>WikiLeaks</em> founder <strong><a href="http://en.rsf.org/why-european-nations-must-protect-03-07-2013,44886.html">Julian Assange</a></strong>, 2013 will be remember for the National Security Agency computer specialist <strong><a href="http://en.rsf.org/united-states-us-congress-urged-to-create-10-06-2013,44748.html">Edward Snowden</a></strong>, who exposed the mass surveillance methods developed by the US intelligence agencies.
</p><p>
The whistleblower is the enemy. Hence the 35-year jail term imposed on <a href="http://en.rsf.org/united-states-lengthy-prison-term-for-bradley-21-08-2013,45087.html">Private Chelsea/Bradley Manning</a> for being the big WikiLeaks source, an extremely long sentence but nonetheless small in comparison with the 105-year sentence requested for freelance journalist <strong><a href="http://en.rsf.org/united-states-for-investigating-private-11-07-2013,44924.html">Barrett Brown</a></strong> in a hacking case. Amid an all-out hunt for leaks and sources, 2013 will also be the year of the <i>Associated Press</i> scandal, which came to light when the Department of Justice acknowledged that it had seized the news agency’s phone records.
</p><p>
While investigative journalism is under threat in the United States, day-to-day reporting exposes journalists to physical danger in Brazil. With five journalists killed in 2013, Brazil has become the western hemisphere’s deadliest country for media personnel, the position held until then by Mexico, a much more dangerous country.
</p><p>
These tragic deaths in Brazil are obviously also due to a high level of violence. Organized crime’s hold on certain regions makes covering subjects such as corruption, drugs or illegal trafficking in raw materials very risky. The crime rings defend themselves. So do government officials, sometimes using force but more often judicial proceedings. <strong><a href="http://en.rsf.org/brazil-local-courts-allow-multiple-25-02-2011,39629.html">Lúcio Flávio Pinto</a></strong>, a journalist and campaigner against trafficking in precious wood has been the target of no fewer that 33 prosecutions and lawsuits. It is a paradox of the 2009 repeal of the 1967 media law inherited from the military dictatorship that compliant courts are now jammed with requests by politicians for censorship orders against news media and journalists
</p><p>
Many of these politicians are what are called “colonels” – governors or parliamentarians who own the state they represent. They own or control local newspapers and radio stations while, at the national level, ten families control the broadcast media. This media model, which limits pluralism, was one of the targets of the “Brazilian spring” protests that were forcibly dispersed. The giant has been slow to overhaul this model, to the detriment of the many community and alternative media.
</p>
&nbsp;
<div>
<h6><b>Brazil - not so sunny spring</b></h6>
<p>News providers were among those hit by the major police crackdown in Brazil in 2013. The large-scale protests that erupted in São Paulo in June in response to public transport fare hikes spread to the rest of the country, fuelled by discontent about the massive spending on the 2014 Football World Cup and the 2016 Olympics. The “Brazilian spring” protests raised questions about the dominant media model and highlighted the appalling methods still used by the state military police since the time of the dictatorship. In the course of the protests, around 100 journalists were the victims of acts of violence, of which more than two thirds were blamed on the police.
</p>

</div>
<h5>CLAMOUR ON THE LEFT FOR MEDIA REGULATION</h5>
<div>
<p>
Are broadcast frequencies easier to redistribute than parcels of land? Agrarian reform has long been a rallying cry in a Latin America notorious for social inequality. It has found an echo in a challenge taken up by progressive governments in the south of the region – the democratization of the media.
</p><p>
Like the land itself, the Latin American media landscape is distinguished by a very high concentration of ownership, by media oligopolies that are a reflection of local and national oligarchies. This has allowed the perpetuation of broadcast media configurations that were established or confirmed under the military dictatorships of the 1960s and 70s, when the media were a controlled preserve.
</p><p>
The end of systematic censorship has unfortunately not ended this high concentration of ownership, which still constitutes an obstacle to real pluralism. Brazil, <a href="http://en.rsf.org/chile.html">Chile</a> and Colombia are all good examples. Even more serious are the incestuous links between the dominant media and the power centres that dictate the political agenda in certain countries. These dominant media played a key role in the coups d’état in Honduras in 2009 and Paraguay in 2012.
</p><p>
In other countries, this media model has been challenged by progressive governments that came to power in elections during the first decade of this century. But with what agenda? Are they just regulating broadcasting and providing a legislative framework for the media and journalists? The answers to these questions vary a great deal from country to country although polarization is a common feature.
</p><p>
In Argentina and <a href="http://en.rsf.org/uruguay.html">Uruguay</a>, broadcasting is in the process of being overhauled in an effective manner by a similar law called (in both countries) the Broadcasting Communication Services Law (LSCA). Adopted in 2009, Argentina’s LSCA was the pioneer of this kind of legislation, reserving a third of broadcast frequencies to non-profit organizations. Such a provision would provide a real opportunity to Latin America’s many community broadcasters, who are denied legal frequencies and, by extension, are often criminalized.
</p><p>
Because of its anti-oligopoly provisions, Argentina’s LSCA inevitably encountered opposition from the Clarín group, the country’s biggest media conglomerate, which has been in open conflict with President Cristina Kirchner since 2008. After a four-year legal battle, the supreme court ruled on 29 October 2013 that two articles challenged by <em>Clarín</em> <a href="http://en.rsf.org/argentina-new-broadcast-media-law-is-30-10-2013,45397.html">were constitutional</a>. One limits the overall number of broadcast licences that can be held by any one company. The other limits the percentage of the market that can be held by a company in any one region.
</p>
<div class="encadre">
<h6><b>Uruguay’s­ model legislation</b></h6>
<p>Approved by the Chamber of Deputies on 10 December 2013, <a href="http://en.rsf.org/uruguay-deputies-pass-amended-broadcasting-12-12-2013,45603.html">Uruguay’s Broadcasting Communication Services Law</a> (LSCA) could become even more of a regional model of broadcasting regulation than Argentina’s LSCA. Uruguay’s adoption of a community radio law in 2007 had already established it as a regional pioneer.
</p><p>
Its LSCA reallocates broadcasting frequencies, assigning a third to commercial stations, a third to state-owned stations and a third to community stations. The law also includes a major guarantee in the form of a ban on any discretionary allocation of frequencies influenced by a station’s editorial policies. The LSCA’s success is favoured by the limited media polarization in Uruguay, compared with neighbouring countries, and the major debate involving civil society that accompanied its drafting.
</p>
</div>
<p>The provisions of Argentina’s LSCA have directly influenced legislation in other countries in the region aimed at ensuring a fair distribution of frequencies according to the type of broadcaster (commercial, public and community). The 2011 reform of the telecommunications law in Bolivia adopts this principle. So too does the communication law that Ecuador adopted in June 2013. Ecuador’s law continues to be criticized for insisting that news coverage must be “accurate, opportune, balanced, contextualized and of public interest.”
</p><p>
Ecuador’s government now has a legislative weapon against the country’s often aggressive and much criticized privately-owned media. It can also count on a chain of state-owned media (or media that it has taken over), which is now dominant at the national broadcast frequency level. And finally it can use the allocation of state advertising, which is essential to the survival of many privately-owned media in the region. In Venezuela, the war between state and privately-owned media dating back to an abortive coup in 2002 has counted for more than any form of regulation. The national airwaves are now almost entirely dominated by the government and its obligatory announcements, called <i>cadenas</i>.
</p>
</div>

<?php include "en-footer.php" ?>