<?php include "en-header.php" ?>


<h2 style="text-align: left;" align="center">Biggest rises and falls in the 2014 World Press Freedom Index</h2>
<p id="intro">
The 2014 World Press Freedom Index spotlights the negative impact of conflicts on freedom of information and its protagonists. The ranking of some countries has also been affected by a tendency to interpret national security needs in an overly broad and abusive manner to the detriment of the right to inform and be informed. This trend constitutes a growing threat worldwide and is even endangering freedom of information in countries regarded as democracies.
Finland tops the index for the fourth year running, closely followed by Netherlands and Norway, like last year. At the other end of the index, the last three positions are again held by Turkmenistan, North Korea and Eritrea, three countries where freedom of information is non-existent. Despite occasional turbulence in the past year, these countries continue to be news and information black holes and living hells for the journalists who inhabit them.
This year’s index covers 180 countries, one more than last year. The new entry, Belize, has been assigned an enviable position (29th). Cases of violence against journalists are rare in Belize but there were some problems: defamation suits involving demands for large amounts in damages, national security restrictions on implementation of the Freedom of Information Act and sometimes unfair management of broadcast frequencies.
</p>
<div id="more">
&nbsp;
<h5>FALLS DUE TO ARMED CONFLICTS</h5>
<p>
The 2014 index underscores the negative correlation between freedom of information and conflicts, both open conflicts and undeclared ones. In an unstable environment, the media become strategic goals and targets for groups or individuals whose attempts to control news and information violate the guarantees enshrined in international law, in particular, article 19 of the International Covenant on Civil and Political Rights, the 1949 Geneva Conventions and the 1977 Protocols Additional 1 and 2 to the Geneva Conventions.
</p><p>
Syria (unchanged at 177th) has been an extreme example of this since March 2011. Now one of the countries where freedom of information and its actors are most in danger, it rubs shoulders with the bottom three. The Syrian crisis has also had dramatic repercussions throughout the region, reinforcing media polarization in Lebanon (106th, -4), encouraging the Jordanian authorities to tighten their grip, and accelerating the spiral of violence in Iraq (153rd, -2), where tension between Shiites and Sunnis is growing.
</p><p>
In Iran (173rd, +2), one of the Middle East’s key countries, there has so far been no implementation of the <a href="http://en.rsf.org/iran-rouhani-s-first-100-days-see-no-19-11-2013,45474.html">promises to improve freedom of information that the new president, Hassan Rouhani, made</a>. Coverage of the Syrian tragedy in both the official Iranian press and on the blogosphere is closely watched by the regime, which cracks down on any criticism of its foreign policy.
</p><p>
This negative correlation is also seen in the big falls registered by Mali (122nd, -22) and Central African Republic (109th, -34). The open or internecine warfare destabilizing Democratic Republic of Congo (151st, -8) and the activities of guerrillas and terrorist groups in Somalia (176th, unchanged) and Nigeria (112th, +4) prevented any significant improvement in their ranking.
</p><p>
The formation of a government led by Mohamed Morsi in Egypt (159th, unchanged) in the summer 2012 was accompanied by an <a href="http://en.rsf.org/egypt-mounting-freedom-of-information-27-06-2013,44862.html">increase in abuses against journalists and all-out efforts to bring the media under the Muslim Brotherhood’s control</a>. That was brought to a complete halt by the army’s return to power a year later. The ensuing persecution of the Muslim Brotherhood affected not only Egyptian journalists but also their Turkish, Palestinian and Syrian colleagues. In the Persian Gulf, especially the United Arab Emirates (118th, -3), <a href="http://en.rsf.org/emirats-arabes-unis-journalist-held-incommunicado-02-08-2013,45013.html">bloggers and journalists were arrested and tried on charges of links to the Brotherhood</a>.
</p><p>
The upsurge in violence against journalists finally elicited a response from the international community – in terms of resolutions, at least. <a href="http://en.rsf.org/un-general-assembly-adopts-26-11-2013,45512.html">The United Nations General Assembly adopted its first-ever resolution on the safety of journalists by consensus on 26 November</a>. It included a call for 2 November to be celebrated as International Day to End Impunity for crimes of violence against journalists.
</p><p>
It was unquestionably a step in the right direction, complementing Resolution 1738 condemning attacks on journalists in armed conflicts, which the Security Council adopted in December 2006 on Reporters Without Borders’ initiative, and the UN Plan of Action on the Safety of Journalists and Impunity, adopted in April 2012. Reporters Without Borders now wants the UN to create a group of independent experts with the task of monitoring respect by member states for their obligations, in particular, their obligation to protect journalists, to investigate all cases of violence against them, and bring those responsible to justice.
</p>
<h5>INFORMATION SACRIFICED TO NATIONAL SECURITY AND SURVEILLANCE</h5>
<p>Countries that pride themselves on being democracies and respecting the rule of law have not set an example, far from it. Freedom of information is too often sacrificed to an overly broad and abusive interpretation of national security needs, marking a disturbing retreat from democratic practices. Investigative journalism often suffers as a result.
</p><p>
This has been the case in the United States (46th), which fell 13 places, one of the most significant declines, amid increased efforts to track down whistleblowers and the sources of leaks. The trial and <a href="http://en.rsf.org/united-states-lengthy-prison-term-for-bradley-21-08-2013,45087.html">conviction of Private Bradley Manning</a> and the <a href="http://en.rsf.org/why-european-nations-must-protect-03-07-2013,44886.html">pursuit of NSA analyst Edward Snowden</a> were warnings to all those thinking of assisting in the disclosure of sensitive information that would clearly be in the public interest.
</p><p>
US journalists were stunned by the <a href="http://en.rsf.org/united-states-seizure-of-ap-phone-records-14-05-2013,44616.html">Department of Justice’s seizure of <i>Associated Press</i> phone records</a> without warning in order to identify the source of a CIA leak. It served as a reminder of the <a href="http://en.rsf.org/united-states-recommendations-for-a-federal-law-17-05-2013,44624.html">urgent need for a “shield law” to protect the confidentiality of journalists’ sources</a> at the federal level. The revival of the legislative process is little consolation for <a href="http://en.rsf.org/united-states-one-step-forward-two-steps-back-29-07-2013,44986.html">James Risen of <i>The New York Times</i>, who is subject to a court order to testify against a former CIA employee accused of leaking classified information</a>. And less still for <a href="http://en.rsf.org/united-states-for-investigating-private-11-07-2013,44924.html">Barrett Brown, a young freelance journalist facing 105 years in prison</a> in connection with the posting of information that hackers obtained from Statfor, a private intelligence company with close ties to the federal government.
</p><p>
The United Kingdom (33rd, -3) distinguished itself in the war on terror by the <a href="http://en.rsf.org/uk-government-s-culpable-20-08-2013,45073.html">disgraceful pressure it put on <i>The Guardian</i> newspaper</a> and by its <a href="http://en.rsf.org/united-kingdom-snowden-journalist-glenn-greenwald-19-08-2013,45062.html">detention of David Miranda</a>, journalist Glenn Greenwald’s partner and assistant, for nine hours. Both the US and UK authorities seem obsessed with hunting down whistleblowers instead of adopting legislation to rein in abusive surveillance practices that negate privacy, a democratic value cherished in both countries.
</p><p>
The <a href="http://en.rsf.org/japan-prime-minister-shinzo-abe-urged-to-27-11-2013,45515.html">“special intelligence protection bill”</a> that the National Diet in Japan (59th, - 5) adopted in late 2013 would reduce government transparency on such key national issues as nuclear power and relations with the United States, now enshrined as taboos. Investigative journalism, public interest and the confidentiality of journalists’ sources are all being sacrificed by legislators bent on ensuring that their country’s image is spared embarrassing revelations.
</p><p>
The “war on terror” is also being exploited by governments that are quick to treat journalists as “threats to national security.” Dozens of journalists have been jailed on this pretext in Turkey (154th), especially for covering the Kurdish issue. In Morocco, unchanged in 136th position, the authorities readily confused journalism with terrorism since the <a href="http://en.rsf.org/morocco-before-hearing-call-to-drop-20-12-2013,45652.html">case of online newspaper editor Ali Anouzla</a>. In Israel (96th, +17), freedom of information is often sacrificed to purported security requirements.
</p><p>
In India’s northern Kashmir region, <a href="http://en.rsf.org/india-news-media-and-internet-totally-13-02-2013,44066.html">mobile Internet and communications are suspended in response to any unrest</a>. In the north of Sri Lanka (165th, -2), the army reigns supreme, tolerating no challenge to the official vision of the “pacification” process in Tamil separatism’s former strongholds. Alarmed by the Arab Spring turmoil, authoritarian regimes in the Arabian Peninsula and Central Asia have stepped up media censorship and surveillance to head off any “attempt at destabilization.”
</p>
<div>
<h5>PRIVATIZATION OF VIOLENCE</h5>
<p>Non-state groups constitute the main source of physical danger for journalists in a number of countries. The militias fomenting chaos in the new Libya (137th, -5) and Yemeni armed groups linked to Al-Qaeda in the Arabian Peninsula are leading examples of this privatization of violence. Al-Shabaab in Somalia (176th, unchanged) and the M23 movement in Democratic Republic of Congo (151st, -8) both regard journalists as enemies. Jihadi groups such as Jabhat Al-Nosra and <a href="http://en.rsf.org/iraq-isis-major-threat-to-media-freedom-30-12-2013,45680.html">Islamic State in Iraq and the Levant (ISIS)</a> use violence against news providers as part of their drive to control the regions they “liberate.”
</p><p>
Organized crime is a fearsome predator for journalists in many parts of the world, especially Honduras (129th, -1), Guatemala (125th, -29), Brazil (111th, -2) and Paraguay (105th, -13), but also Pakistan, China, Kyrgyzstan and the Balkans. In organized crime’s shadow, it is hard if not impossible to refrain from self-censorship on such sensitive subjects as drug-trafficking, corruption and criminal penetration of the state apparatus. The passivity or indifference often shown by authorities towards crimes of violence against the media, or sometimes even their connivance or direct involvement, reinforces the impunity enjoyed by those responsible and fuels the cycle of violence against news providers.
</p><div>
<p>
L’indice annuel de la liberté de la presse, inauguré lors du Classement 2013, confirme une dégradation, à l’échelle mondiale, de la situation du droit d’informer et d’être informé. L’indice passe de 3 395 à 3 456 (+61), soit une augmentation de 1,8 % qui révèle une légère dégradation globale de la liberté de l’information entre l’édition 2013 et l’édition 2014 du Classement mondial.Si l’année 2013 a été moins meurtrière pour les journalistes que la précédente, marquée par une hécatombe pour la profession, les agressions et menaces ont été plus nombreuses. La hausse de l’indice s’explique par l’évolution non seulement des exactions, mais aussi de l’ensemble des indicateurs utilisés pour compiler le classement :
</p><p>
— Pluralism, meaning the representation of different views in the media;
— Independence of the media vis-à-vis political, economic, religious and military centres of power;
— Quality of the legislation governing the media;
— Transparency of the bodies regulating the media;
— Performance of the infrastructure supporting the media;
— Overall climate for freedom of information.
</p><p>
The indicator is a tool for measuring overall performance. The breakdown of the indicator’s scores by region shows a worsening in all continents except Asia, where it was unchanged. Like last year, the European Union and Balkans obtained the best score (17.6), followed by the Americas (30.3), Africa (35.6), Asia-Pacific (42.2), Eastern Europe and Central Asia (45.5) and finally Middle East and North Africa (48.7).
</p><p>
<strong>Annual media freedom indicator</strong>: 3456 in 2014 (3395 in 2013)
<ul>
	<li>European Union and Balkans: 17.6 (17.5)</li>
	<li>Americas: 30,3 (30,0)</li>
	<li>Africa : 35,6 (34,3)</li>
	<li>Asia-Pacific: 42,2 (42,2)</li>
	<li>Eastern Europe and Central Asia: 45,5 (45,3)</li>
	<li>Middle East and North Africa: 48,7 (48,5)</li>
</ul>
</p>
</div>
<h5></h5>
<h5>NOTEWORTHY FALLS</h5>
<p>In the Americas, the 13-place fall registered by the United States (46th, -13) was more than doubled by Guatemala (125th, -29), which saw a two-fold increase in the number of physical attacks on journalists, including <a href="http://en.rsf.org/guatemala-another-journalist-shot-dead-in-20-08-2013,45078.html">four murders</a>, and was equalled by Paraguay (105th, -13), where the pressure on journalists to censor themselves keeps on mounting. Paraguay had already plummeted last year, following a coup in June 2012, three years after a coup sent Honduras (129th, -1) to the level where it remains in the current post-election chaos.
</p><p>
In Africa, the two most noteworthy falls, by Mali and Central African Republic, were due to armed conflicts mentioned above. In Burundi, where a presidential election is imminent, the <a href="http://en.rsf.org/burundi-new-law-s-promulgation-sets-04-06-2013,44574.html">senate passed a law restricting the freedom of journalists</a>. In Kenya (90th, -18), the government’s much criticized authoritarian response to the media’s coverage of the Westgate Mall attacks was compounded by dangerous parliamentary initiatives, above all a <a href="http://en.rsf.org/kenya-draconian-bill-06-11-2013,45428.html">law adopted at the end of 2013 creating a special court to judge audiovisual content</a>.
</p><p>
In Guinea (102nd, -15), journalists found it dangerous and difficult to work during elections marked by many protests. Several journalists were attacked or injured by over-excited demonstrators or by members of the security forces dispersing the protests. Zambia (93rd, -20), which had progressed in recent years, was dragged down by <a href="http://en.rsf.org/zambie-rwb-publishes-articles-censored-by-02-08-2013,44932.html">measures to censor and block news websites</a>. Finally, rulers who have clung to power for years and fear change got tougher with the media, resulting in abusive prosecutions in Chad (139th, -17) and several closures in Cameroon (131st, -10).
</p><p>
The 13-place fall by Kuwait (91st) reflects the somewhat tougher line pursued by the authorities. A draconian bill was proposed and then abandoned in the spring of 2013. It would have allowed the authorities to fine journalists up to 300,000 dinars (1 million dollars) for criticizing the emir or the crown prince, or misrepresenting what they say, and impose sentences of up to 10 years in prison on journalists who insult God, the Prophets of Islam, or the Prophet Mohamed’s wives or companions.
</p><p>
These spectacular changes should not make us forget the tragic immobility at the bottom of the index where Vietnam (173rd, -1), Uzbekistan (166th, -1) and Saudi Arabia (164th, unchanged), to name but three, continue to tighten their grip on news and information and adapt their methods of radical censorship to the digital era. The cruellest punishments await those of their citizens who have the courage to resist. In Kazakhstan (161st, unchanged) and Azerbaijan (160th, -3), media pluralism is in the process of succumbing to the increasingly repressive tendencies of rulers clinging to power.
</p><h5>NOTEWORTHY RISES</h5>
Violence against journalists, direct censorship and misuse of judicial proceedings are on the decline in Panama (87th, +25), Dominican Republic (68th, +13), Bolivia (94th, +16) and Ecuador (94th, +25), although in Ecuador the level of media polarization is still high and often detrimental to public debate.
</p><p>
The past year was marked by laudable legislative developments in some countries such as South Africa (42nd, +11), where the <a href="http://en.rsf.org/afrique-du-sud-president-refuses-to-sign-12-09-2013,45168.html">president refused to sign a law that would have endangered investigative journalism</a>.
</p><p>
In Georgia (84th, +17), the 2013 presidential election was less tense that the previous year’s parliamentary elections, which were marked by physical attacks and hate campaigns against journalists. Thanks to political cohabitation and then a change of government through the polls, Georgia has recovered some of the terrain lost in recent years as the Saakashvili administration’s reforming zeal ran out of steam. Media polarization will nonetheless continue to be a challenge in the coming years.
</p><p>
Israel’s 17-place rise must be offset against its 20-place fall in the 2013 index as a result of <a href="http://en.rsf.org/palestinian-terr-pillar-of-defence-or-information-19-11-2012,43697.html">Operation “Pillar of Defence” in November 2012</a>, when two Palestinian journalists were killed, and the many raids it carried out against Palestinian media. Security needs continue to be used as an excuse to limit freedom of information. The Israeli media are able to be outspoken but media located in “Israeli territory” must comply with prior military censorship and gag orders. Investigative reporting involving national security is not welcome.
</p><p>
Abusive treatment of Palestinian and foreign journalists by the Israel Defence Forces is common, especially during the weekly demonstrations at the Separation Wall. Many photojournalists were deliberately targeted when leaving the demonstrations in November 2013. On <a href="http://en.rsf.org/israel-disappointing-decision-in-wattan-09-12-2013,45571.html">4 December, an Israeli high court endorsed the seizure of equipment from <i>Wattan TV</i></a> during an IDF raid in February 2012.
</p><p>
Timor-Leste (77th) rose 14 places in the wake of a <a href="http://en.rsf.org/east-timor-rwb-welcomes-creation-of-press-07-11-2013,45436.html">historic journalists’ congress in Dili on 25-27 October</a> at which a code of professional conduct and the creation of a seven-member Press Council were approved. But continuing vigilance is needed. The media law currently before parliament is the next challenge for media freedom in Timor-Leste.
</p>
<h5>REGIONAL MODELS IN DECLINE?</h5>
<p>The movements of some countries in the index, which are indicative of their approach to freedom of information, has an impact not only on their own population but also on neighbouring countries because of their regional importance and influence and the fact that they are regarded – rightly or not – as models to be watched or followed. South Africa’s 11-place rise to 42nd position contrasts with the performance of other countries regarded as regional models, which have either shown no improvement or are in decline.
</p><p>
The European Union’s members are becoming more dispersed in the index, a development accelerated by the effects of the economic crisis and outbreaks of populism. Greece (99th, -14) and Hungary (64th, -7) are the most notable examples. In Greece, <a href="http://en.rsf.org/greece-golden-dawn-close-to-being-added-04-06-2013,44709.html">journalists are often the victims of physical attacks by members of Golden Dawn</a>, the neo-Nazi party that entered parliament in June 2012. The government’s actions have also contributed to the fall. By closing the state broadcaster under pressure from the Troika (the European Commission, European Central Bank and IMF), Prime Minister Antonis Samaras seems to be cutting back on democracy to save money.
</p><p>
In Hungary, Prime Minister Viktor Orban’s government gives the impression of having abandoned EU values in its zeal for draconian reforms. As a direct result of the European model’s erosion, the EU is finding it harder to get membership candidates to improve their position in the index. Membership negotiations are no longer necessarily accompanied by efforts to increase respect for civil liberties. Macedonia (123rd), for example, has never been so low in the index.
</p><p>
The western hemisphere’s giants – United States (46th, -13) and Brazil (111th, -2) – have not set an example either. Since 9/11, the former has been torn by the conflict between national security imperatives and respect for the principles of the First Amendment. Thanks to organized crime’s impact, the latter is one of the continent’s deadliest countries for the media, while its media pluralism is handicapped by the phenomenon of powerful politicians who are also big businessmen and media owners, with the result that Brazil has been dubbed “the country of 30 Berlusconis.”
</p><p>
Russia (148th) might have been lower in the index had it not been for the stubbornness and resistance shown by its civil society. But the <a href="http://en.rsf.org/russia-more-draconian-legislation-how-far-20-12-2013,45650.html">authorities keep on intensifying the crackdown</a> begun when Vladimir Putin returned to the Kremlin in 2012 and are exporting their model throughout the former Soviet Union. From Ukraine (127th, unchanged) and Azerbaijan (160th, -3) to Central Asia, Russia’s repressive legislation and communications surveillance methods are happily copied. Moscow also uses UN bodies and regional alliances such as the Shanghai Cooperation Organization in its efforts to undermine international standards on freedom of information.
</p><p>
Despite its regional aspirations, Turkey (154th) registered no improvement and continues to be one of the world’s biggest prisons for journalists. The Gezi Park revolt highlighted the <a href="http://en.rsf.org/turkey-climate-of-hostility-towards-news-20-06-2013,44825.html">repressive methods used by the security forces</a>, the increase in self-censorship and the dangers of the prime minister’s populist discourse. In view of the upcoming elections and the unpredictability of the peace process with the Kurdish separatists, 2014 is likely to be a decisive year for the future of civil liberties in Turkey.
</p><p>
Chine (175th, -1) failed to improve its ranking because, despite having an astonishing vital and increasingly militant blogosphere, it continues to censor and jail dissident bloggers and journalists. This new power is also using its economic might to extend its influence over the media in Hong Kong, Macau and Taiwan, compromising their independence.
</p><p>
India (140th, +1) experienced an unprecedented wave of violence against journalists, with eight killed in 2013. They are targeted by both state and non-state actors. Almost no region is spared but Kashmir and Chhattisgarh continue to be the only two where violence and censorship are endemic. Those responsible for threats and physical violence against journalists, who are often abandoned by the judicial system and forced to censor themselves, include police and security forces as well as criminal groups, demonstrators and political party supporters.
</p><p>
The substantial reforms in Burma, which could become a regional model for a transition to democracy, were reflected in a big leap in the 2013 index. As the reform process begins to flag, the “Burmese model” has yet to prove itself.
</p>
</div>
</div>

<?php include "en-footer.php" ?>