<?php 
	$selected 	= "ameriques";
	$title 		= "World Press Freedom Index 2014 | AMERICAS"
?>
<?php include "es-header.php" ?>
<h2>América</h2>
<h5>INFORMACIÓN A PRUEBA DE UNA VIOLENCIA MÚLTIPLE</h5>
<p>
Han pasado más de veinte años desde que América Latina y el Caribe dejaron de vivir –o casi– bajo el yugo de las dictaduras militares o bajo el fuego de las guerras civiles. <a href="http://es.rsf.org/colombia.html" target="_blank">Colombia</a> es una excepción, el conflicto armado ha durado medio siglo. <a href="http://es.rsf.org/cuba.html" target="_blank">Cuba</a> también se diferencia por su régimen, heredado de la guerra fría, que no tolera ningún contrapoder independiente, pero que a su vez ve la emergencia de una sociedad civil que lo obliga a replantear su “modelo”. Formalmente ha ganado un ambiente de paz y de instituciones democráticas. Formalmente, pues queda camino por recorrer para salvar la distancia que resta entre la garantía constitucional de las libertades públicas y un verdadero Estado de Derecho. Numerosos periodistas y defensores de los derechos humanos enfrentan todos los días una situación de violencia elevada y múltiple, generada por el crimen organizado, los paramilitares y, a veces, la represión del Estado.
</p><p>
Ejemplo de esta sangrienta confluencia, <a href="http://es.rsf.org/honduras.html" target="_blank">Honduras</a> posee una tasa de homicidios similar a la de países en guerra: se registran en promedio al año 80 asesinatos por cada 100.000 habitantes (el país cuenta en total con sólo siete millones). En Honduras han sido asesinados treinta periodistas en una década; 27 de ellos perdieron la vida después del <a href="http://es.rsf.org/honduras-los-medios-de-comunicacion-en-la-07-09-2009,33696.html" target="_blank">golpe de Estado del 28 de junio de 2009</a>, que derrocó al presidente electo, Manuel Zelaya. En nueve de estos casos se ha comprobado que el crimen estuvo relacionado con su actividad profesional. En este Estado fallido, la impunidad casi absoluta constituye la regla. Los atentados, las amenazas, las agresiones y hasta las “canonizaciones” de ciertos medios de comunicación, son obra tanto de las milicias privadas a sueldo de los terratenientes, del ejército y la policía (de estatus militar), como de los cárteles, muy presentes en la región.
</p><p>
Esto también sucede en América Central y en los Andes. En <a href="http://es.rsf.org/peru.html" target="_blank">Perú</a> y en <a href="http://es.rsf.org/colombia.html" target="_blank">Colombia</a> la cobertura del narcotráfico, de la corrupción y de los conflictos territoriales o mineros incrementa en gran medida el riesgo de que los periodistas padezcan represalias. La esperanza –pequeña, pero real– de que pronto el gobierno de Bogotá y la guerrilla de las Fuerzas Armadas Revolucionarias de Colombia (FARC) logren establecer un acuerdo de paz, no puede borrar la existencia del narco-paramilitarismo, también heredado de los años de guerra. ¿Cuántos periodistas –y junto con ellos sindicalistas, abogados y representantes de asociaciones– padecen la presión, a menudo fatal, de unidades paramilitares reconstituidas como los <a href="http://es.rsf.org/predator-otoniel-y-los-urabenos-paramilitares,44491.html" target="_blank">Urabeños o los Rastrojos</a>?
</p><p>
En <a href="http://es.rsf.org/mexico.html" target="_blank">México</a> estos predadores se llaman <a href="http://es.rsf.org/predator-mexico-miguel-trevino-morales-alias-z-40-y-el-cartel-de-los-zetas,44503.html" target="_blank">Zetas</a>, aunque existen otras organizaciones criminales que actúan con la complicidad de las autoridades locales –y a veces federales– corruptas. El país arrastra un terrible balance: 88 periodistas asesinados y 18 desaparecidos entre 2000 y 2013; situación agravada por la llamada “ofensiva federal contra el narcotráfico”, emprendida bajo la presidencia de Felipe Calderón (2006-2012), que dejó como saldo más de 60 mil muertos.
</p><p>
Más al sur, en países como <a href="http://es.rsf.org/brasil.html" target="_blank">Brasil</a> y <a href="http://es.rsf.org/paraguay.html" target="_blank">Paraguay</a>, el crimen organizado y su infiltración también obstaculizan la investigación y la información. En estos países, como sucede en los otros, la frágil condición de periodista se debe con frecuencia a su falta de estatus y a la poca solidaridad entre el gremio, pero también a la trágica sumisión de los medios de comunicación, sobre todo regionales, a los centros de poder. Verdadero esguince en el pluralismo y la independencia de la prensa, el <a href="http://es.rsf.org/bresil-o-pais-dos-trinta-berlusconis-os-24-01-2013,43939.html" target="_blank">“colonialismo” brasileño</a> hace que el periodismo se convierta en instrumento de los barones locales, a la merced de los ajustes de cuentas políticos, en ocasiones mortales.
</p><p>
El periodista, junto con su medio de comunicación, también es un juguete político en los países que viven una fuerte polarización, en los que la oposición entre el sector privado y el público –o más bien el Estado– tiende al enfrentamiento. <a href="http://es.rsf.org/venezuela.html" target="_blank">Venezuela</a> lo ilustra de manera extrema. Los numerosos periodos electorales multiplicaron las ocasiones de invectivas y agresiones en el país. Este clima también se vive en <a href="http://es.rsf.org/ecuador.html" target="_blank">Ecuador</a>, <a href="http://es.rsf.org/bolivia.html" target="_blank">Bolivia</a> y, en menor medida, <a href="http://es.rsf.org/argentina.html" target="_blank">Argentina</a>.
</p>
<h5>ESTADOS UNIDOS, BRASIL: LOS GIGANTES DEL NUEVO MUNDO NO PONEN EL EJEMPLO</h5></p><p>
<p>Uno es una superpotencia; el otro, una potencia emergente. Uno encarnó durante mucho tiempo la democracia consolidada, donde las libertades públicas reinan. El otro, con el apoyo de una Constitución democrática adoptada solamente tres años después del final de su dictadura (1964-1985), creó durante la presidencia de Luiz Inacio Lula da Silva (2003-2010) las condiciones de desarrollo de una sociedad civil poderosa. Ricos en sus diversidades, <a href="http://es.rsf.org/estados-unidos.html" target="_blank">Estados Unidos</a> y Brasil deberían poner en lo más alto la libertad de información, como norma jurídica y como valor. Por desgracia, la realidad está muy lejos de ser así.
</p><p>
En Estados Unidos, el 11 de septiembre de 2001 generó un profundo dilema entre: los imperativos de la seguridad nacional y los principios de la primera enmienda de la Constitución, que consagra el derecho de todo individuo a informar y a ser informado. La base constitucional de 1776 se estremeció con fuerza desde sus cimientos durante el doble mandato de George W. Bush, debido a las presiones, incluso el encarcelamiento, de ciertos periodistas que se negaban a revelar la identidad de sus fuentes o sus archivos a la justicia federal.
</p><p>
Desde que Barack Obama asumió sus funciones, la situación no ha mejorado sobre el fondo. ¿Ya no se persigue al periodista? Se caza a su fuente, usándolo a veces como ojeador. Al menos ocho personas han sido objeto de procesos legales con base en la <a href="http://es.rsf.org/estados-unidos-el-abuso-de-la-espionage-act-es-22-05-2013,44654.html" target="_blank">ley de espionaje</a> (Espionage Act) desde que Barack Obama llegó al poder; bajo el gobierno de Bush fueron tres. El año 2012 fue en parte el de <strong><a href="http://es.rsf.org/por-que-los-paises-de-europa-deben-04-07-2013,44888.html" target="_blank">Julian Assange</a></strong>, fundador de WikiLeaks. Con el año 2013 se recordará el nombre de <strong><a href="http://es.rsf.org/estados-unidos-rsf-pide-al-congreso-11-06-2013,44753.html" target="_blank">Edward Snowden</a></strong>, informático subcontratado de la Agencia de Seguridad Nacional (National Security Agency, NSA), quien dio a conocer los programas de vigilancia masiva desarrollados por los servicios de inteligencia de Estados Unidos. El “informante”, he allí el enemigo. De allí la pena de 35 años de prisión infligida al <a href="http://es.rsf.org/estados-unidos-sentencian-a-bradley-manning-a-35-21-08-2013,45088.html" target="_blank">soldado Manning</a>, acusado de ser el “topo” de <em>WikiLeaks</em>.
</p><p>
Una pena muy pequeña comparada con la que enfrenta el periodista independiente <strong><a href="http://es.rsf.org/estados-unidos-acusado-de-ser-un-hacker-el-11-07-2013,44926.html" target="_blank">Barrett Brown</a></strong>, acusado de ser un hacker: 105 años de prisión. En un ambiente generalizado de rastreo de fuentes y de datos, el año 2013 quedará marcado por el escándalo de <em>The Associated Press</em>, provocado por la obtención, por parte del Departamento de Justicia, de los historiales de llamadas telefónicas de la agencia informativa.
</p><p>
En el norte, el periodismo de investigación vacila. En el sur, el periodismo diario aún es sinónimo de riesgos y peligros. Brasil, donde fueron asesinados cinco periodistas en el año 2013, se sitúa como el país más mortífero del continente para el gremio, un lugar que ocupaba hasta ahora un México mucho más sangriento.
</p><p>
Brasil le debe estas tragedias a su inseguridad, aún elevada. El crimen organizado se impone en algunas regiones, lo que vuelve peligroso abordar temas como la corrupción, la droga o el tráfico de materias primas. Las mafias vigilan. Las autoridades también; reprimiendo a veces con las armas, castigan muy duramente con procesos legales. <strong><a href="http://es.rsf.org/brasil-avalancha-de-acoes-judiciais-25-02-2011,39628.html" target="_blank">Lúcio Flávio Pinto</a></strong>, periodista y bloguero que denunciaba el tráfico de maderas preciosas, enfrenta al menos 33 procesos judiciales. Paradoja de la revocación –en 2009– de la Ley de Prensa de 1967 heredada del régimen militar: las órdenes de censura a medios de comunicación y periodistas atiborran actualmente los tribunales, a petición de políticos que se sirven de una justicia complaciente.
</p><p>
Estos políticos son a menudo los llamados “coroneles”, gobernadores o parlamentarios dueños de su Estado, quienes localmente colonizan publicaciones y frecuencias audiovisuales. Mientras tanto, a escala nacional diez grandes grupos familiares se reparten el espacio de difusión. La “primavera brasileña”, duramente reprimida, también incluía la protesta contra un modelo mediático que se ha convertido en un obstáculo para el pluralismo. En perjuicio de numerosos medios de comunicación comunitarios y alternativos, el gigante tarda en reformarse en este sentido.
</p>
<div class="encadre">
<h6>Brasil: una “primavera” emplomada</h6></p><p>
<p>La fuerte represión policíaca que padeció Brasil en 2013 también afectó a los actores de la información. En el mes de junio estallaron importantes protestas por el anuncio de un aumento del precio del transporte público en São Paulo. La agitación se extendió por todo el país. La población tampoco aceptaba los gastos faraónicos hechos por el gobierno con miras a la Copa Mundial de Fútbol que se llevará a cabo en 2014 y los Juegos Olímpicos, que realizarán en 2016. Esta “primavera brasileña” también dio lugar a un fuerte cuestionamiento del modelo mediático dominante. Finalmente, puso de manifiesto las siniestras costumbres que conservan las policías militares de los Estados desde la época de la dictadura. Una centena de periodistas padeció la violencia durante las manifestaciones; más de dos tercios de estas agresiones se atribuyen a las fuerzas del orden.
</p>
</div>
<h5>L</p><p>A REGULACIÓN DEL PAISAJE MEDIÁTICO, NUEVA BASTILLA DE LAS IZQUIERDAS DEL CONTINENTE</h5>
<div>
<p>
¿Las frecuencias audiovisuales se redistribuyen más fácilmente que las porciones de tierra? Sabemos cuánto la reforma agraria constituye, desde hace mucho, una marca de identidad para América Latina, que durante largo tiempo ha sido la campeona de las desigualdades sociales. Esta cuestión se encuentra presente de cierta forma en los retos actuales de los gobiernos progresistas del sur de la región: la democratización de las plataformas informativas y de difusión.
</p><p>
Al igual que el terreno cultivable, el campo mediático latinoamericano se distingue porque se concentra en pocas manos; los medios son escaparates de las oligarquías locales y nacionales. Este <i>statu quo</i> prevaleció gracias a mecanismos de radiodifusión consolidados bajo las dictaduras militares de los años 1960 y 1970, cuando los medios de comunicación constituían un coto privado bajo control. Por desgracia, el fin de la censura sistemática no acabó con la excesiva concentración de los medios, que aún obstaculiza un verdadero pluralismo. Brasil, <a href="http://es.rsf.org/chile.html" target="_blank">Chile</a> y Colombia ilustran esta situación. Más grave aún, las relaciones incestuosas entre los medios de comunicación dominantes y los centros de poder todavía dictan la agenda política en algunos países. Estos mismos medios de comunicación dominantes jugaron un rol clave en el golpe de Estado de Honduras, en 2009, y el golpe parlamentario de Paraguay, en 2012.
</p><p>
Por otra parte, el modelo mediático experimenta un profundo cuestionamiento, impulsado por los gobiernos progresistas que llegaron al poder con la ola electoral de los años 2000. Pero, ¿se trata de regular el espacio de difusión o a los medios de comunicación y sus actores? Las respuestas que pueden dar los países a esta pregunta contrastan mucho, en un ambiente de polarización.
</p><p>
Tanto en Argentina como en <a href="http://es.rsf.org/uruguay.html" target="_blank">Uruguay</a> se realiza una estricta reforma del marco audiovisual, a favor de legislaciones llamadas –por ambas partes del Río de la Plata– Ley de Servicios de Comunicación Audiovisual (LSCA). La LSCA argentina, aprobada en 2009, fue pionera en su género porque reserva un tercio de las frecuencias audiovisuales a organismos sin fines de lucro. Esta disposición ofrece una verdadera oportunidad a medios de comunicación comunitarios, que abundan en el continente, pero que carecen de medios de transmisión e incluso son criminalizados. Debido a sus cláusulas que buscan evitar la concentración de medios y frecuencias en pocas manos, la LSCA lógicamente contraría los intereses del grupo <em>Clarín</em>, en conflicto abierto con la presidenta Cristina Kirchner desde 2008. Tras cuatro años de lucha judicial, el 29 de octubre de 2013 la Suprema Corte de Justicia de la Nación <a href="http://es.rsf.org/la-suprema-corte-de-justicia-de-la-30-10-2013,45398.html" target="_blank">declaró constitucionales</a> los dos artículos por los cuales el grupo había interpuesto un recurso legal. Esto le impone ceder una parte de sus frecuencias audiovisuales y le impide que pueda ser a la vez, en la misma localidad, concesionario de un canal abierto y propietario de una empresa de producción y distribución televisual por cable.
</p>
<div class="encadre">
<h6>Uruguay: un modelo de legislación</h6></p><p>
<p>Votada en la Cámara de Diputados el 10 de diciembre de 2013, <a href="http://es.rsf.org/uruguay-ajustes-y-un-nuevo-reto-para-la-12-12-2013,45602.html" target="_blank">la Ley de Servicios de Comunicación Audiovisual</a> (LSCA) podría convertirse en una referencia en materia de regulación de los medios de comunicación. El país fue pionero en la región con una ley <i>ad hoc </i>de radios comunitarias, adoptada en 2007. La LSCA contempla redistribuir las frecuencias audiovisuales en tres partes iguales entre los diferentes medios de comunicación: privados, públicos y comunitarios. Asimismo, la LSCA ofrece una garantía importante al prohibir que se otorguen licencias de difusión de forma discrecional, según la línea editorial de las estaciones y los canales. El que exista poca polarización entre los medios de comunicación de este país –en comparación con sus vecinos– favorece a la nueva ley, al igual que el amplio debate que precedió su elaboración y que reunió a los diferentes actores de la sociedad civil.
</p>
</div>
<p>Las disposiciones generales de la LSCA tuvieron una influencia directa en otras legislaciones de la región encaminadas a una distribución equitativa de las frecuencias audiovisuales entre los diferentes tipos de medios de comunicación (públicos, privados y comunitarios). La reforma de la Ley de Telecomunicaciones de Bolivia (2011) contempló este principio, al igual que la Ley Orgánica de Comunicación de Ecuador, adoptada el 14 de junio de 2013. Sin embargo, esta última sigue siendo criticada, pues establece que la información “de relevancia pública” de los medios de comunicación sea “verificada, contrastada, contextualizada y oportuna”.
</p><p>
Frente a los medios de comunicación privados –que con frecuencia son agresivos y desprestigian entre ellos mismos– el gobierno ecuatoriano cuenta ahora con el arma legal. También con un conjunto de medios de comunicación públicos o bajo su tutela (<i>incautados)</i>, que ahora predominan entre las frecuencias nacionales. Finalmente puede valerse del gran maná que representa la publicidad oficial, indispensable para la supervivencia de numerosos medios de comunicación regionales. En Venezuela, la lógica de “guerra mediática” –que nació con el golpe de Estado de 2002– ha llevado al gobierno a buscar toda forma de regulación. El espacio audiovisual nacional está sometido casi por completo al Poder Ejecutivo y a sus <i>cadenas</i> (mensajes oficiales que se transmiten en cadena nacional y cuya difusión es obligatoria).
</p>
</div>

<?php include "es-footer.php" ?>