<?php 
	$title 		= "World Press Freedom Index 2014";
?>
<?php include "es-header.php" ?>

<h1 style="text-align: left;" align="center">Las grandes evoluciones en la edición 2014 de la Clasificación Mundial de la Libertad de Prensa</h1>
<p id="intro">
	<img class="left" src="/data/couvIndex-en.png" alt="couverture classement 2014"/>
	La edición 2014 de la "Clasificación Mundial de la Libertad de Prensa” revela el impacto negativo de los conflictos armados en la libertad de información y en sus actores. La posición de algunos países también se vio afectada porque estos han hecho una interpretación demasiado amplia y abusiva del concepto de “protección de la seguridad nacional”, a costa del derecho de informar y de ser informado. Esta tendencia constituye una amenaza creciente a escala global, peligrosa para la libertad de información hasta el corazón mismo del “Estado de Derecho”.</p>
<div id="more">
<p>
Finlandia conserva su lugar como el mejor de la clase, ocupa por cuarto año consecutivo el primer sitio de la clasificación. Al igual que en la última edición, le pisan los talones los Países Bajos y Noruega. En el extremo opuesto, al final de la clasificación, se encuentra el “trío infernal”, que de nuevo reúne a Turkmenistán, Corea del Norte y Eritrea, países donde la libertad de prensa simplemente no existe. A pesar de que en 2013 se vieron atravesados por algunas turbulencias, estos países siguen siendo hoyos negros de la información y verdaderos infiernos para los periodistas.
</p><p>
Este año la clasificación incluye a 180 países, la edición precedente estaba conformada por 179. Nuevo integrante: Belice, que se ubica de entrada en un lugar envidiable (29°). Los casos de violencia contra periodistas son raros en este país. No obstante, existen algunos bemoles: procesos judiciales por “difamación” en los que se piden altas indemnizaciones por daños y prejuicios; en nombre de la seguridad nacional se hacen algunas excepciones que afectan la buena aplicación de la Ley de Acceso a la Información Pública (Freedom of Information Act); en ocasiones el gobierno no gestiona las frecuencias audiovisuales de forma equitativa.
</p>
<h5>CONFLICTOS ARMADOS, FACTORES DE CAÍDAS</h5>
<p>
La clasificación 2014 subraya la lógica correlación negativa que existe entre un conflicto –abierto o no declarado– y la libertad de información. En un contexto de inestabilidad los medios de comunicación son objetivos y blancos estratégicos para los grupos o los individuos que intentan controlar la información, en violación de las garantías que ofrecen los acuerdos internacionales, en particular el artículo 19 del Pacto Internacional de Derechos Civiles y Políticos, los Convenios de Ginebra de 1949 y sus Protocolos adicionales I y II de 1977.
</p><p>
Desde marzo de 2011 Siria (177°, 0) encarna este tipo de casos en extremo, al punto de que ahora es uno de los países donde la libertad de información y sus actores corren más peligro, a las puertas del “trío infernal”. Asimismo, la crisis siria tiene repercusiones dramáticas en toda la región. Consolidando la línea de fractura entre los medios de comunicación en Líbano (106°, -4), de por sí ya polarizados, incita a las autoridades jordanas a apretar aún más y acelera la espiral de violencia que mina Irak (153°, -2), donde las tensiones religiosas entre chiitas y sunitas se exacerban. En Irán (173°, +2), actor clave de la región, las promesas del nuevo presidente, Hasan Rohaní, de mejorar la libertad de información, no se han cumplido por el momento. Las autoridades, que reprimen toda crítica a su política extranjera, vigilan muy de cerca la cobertura de la tragedia siria, tanto de la prensa oficial como de la blogósfera.
</p><p>
La caída de Malí (122°, -22) y de la República Centroafricana (109°, -34) en la clasificación también ilustra dicha correlación negativa. Las guerras abiertas o intestinas que desestabilizan a la República Democrática del Congo (151°, -8), así como las operaciones de guerrillas y de grupos terroristas en Somalia (176°, 0) y en Nigeria (112°, +4), no contribuyen a mejorar su lugar en la clasificación.
</p><p>
En Egipto (159°, 0), la llegada al poder de los Hermanos Musulmanes en el verano de 2012 estuvo acompañada de un recrudecimiento de las exacciones a periodistas y de una apropiación de los medios de comunicación por parte de la hermandad, frenada un año más tarde. Desde que el ejército regresó al poder, la “caza a los Hermanos” afecta a los periodistas egipcios, así como a sus colegas turcos, palestinos y sirios. En los países del Golfo Pérsico –en particular en los Emiratos Árabes Unidos (118°, -3)–, actores de la información son detenidos y juzgados, acusados de tener nexos con la hermandad.
</p><p>
Frente al recrudecimiento de la violencia, la comunidad internacional al fin reacciona –al menos en los textos–. El 26 de noviembre de 2013 la Asamblea General de las Naciones Unidas aprobó por consenso la primera resolución sobre la seguridad de los periodistas, así como la creación del Día Mundial contra la Impunidad de los Crímenes contra Periodistas, que se celebrará el 2 de noviembre. Esta resolución es sin duda un paso más en la buena dirección y complementa la Resolución 1738, que condena los ataques a periodistas en zonas de conflictos armados, iniciada por Reporteros sin Fronteras y adoptada por el Consejo de Seguridad de las Naciones Unidas en diciembre de 2006, así como el Plan de Acción de las Naciones Unidas sobre la seguridad de los periodistas y la cuestión de la impunidad, adoptado en abril de 2012. Reporteros sin Fronteras pide en particular que la ONU designe un grupo de expertos encargados de evaluar que los Estados miembros cumplan sus obligaciones, en particular la de proteger a los periodistas, investigar todos los actos de violencia y que los responsables de estos rindan cuentas ante la justicia.
</p>
<h5>LA INFORMACIÓN, ¿SACRIFICADA EN ARAS DE LA VIGILANCIA Y LA SEGURIDAD NACIONAL?</h5>
<p>Los países que se jactan de ser un "Estado de Derecho" no dan el ejemplo, están lejos de hacerlo. La libertad de información cede con gran frecuencia ante una concepción de la seguridad nacional demasiado amplia y un uso abusivo de este concepto, lo que marca un retroceso preocupante en las prácticas democráticas. El periodismo de investigación lo padece, en ocasiones gravemente, como sucede en Estados Unidos (46°), que pierde 13 posiciones. Uno de los retrocesos más notables, en medio de una situación en la que el rastreo de fuentes y la caza a informantes van en ascenso. La <a href="http://es.rsf.org/estados-unidos-sentencian-a-bradley-manning-a-35-21-08-2013,45088.html">condena del soldado Bradley Manning</a> o la <a href="http://es.rsf.org/por-que-los-paises-de-europa-deben-04-07-2013,44888.html">persecución del analista de la Agencia de Seguridad Nacional (National Security Agency, NSA), Edward Snowden</a>, son algunas de las advertencias dirigidas a aquellos que se atrevan a filtrar información considerada delicada –pero de interés público comprobado– para que se le dé una divulgación más amplia. El gremio fue sacudido por el escándalo de la obtención, por parte del Departamento de Justicia de Estados Unidos, de los <a href="http://es.rsf.org/estados-unidos-obtencion-de-los-registros-14-05-2013,44615.html">historiales de llamadas telefónicas de la agencia <i>The Associated Press</i> (<i>AP</i>)</a>, para identificar quién le reveló información sobre una operación de la CIA. Este caso recordó la <a href="http://es.rsf.org/etats-unis-recomendaciones-de-rsf-para-una-17-05-2013,44626.html">urgencia de una “ley escudo” federal que garantice la protección de las fuentes de los periodistas</a>. El proceso legislativo reactivado en ese sentido no tranquiliza mucho a <a href="http://es.rsf.org/estados-unidos-un-paso-adelante-dos-hacia-atras-29-07-2013,44988.html">James Risen, periodista de<i> The New York Times</i>, forzado por el Departamento de Justicia a testimoniar en el proceso de un exagente de la CIA en otro caso de filtración de información clasificada</a>. Tampoco permite olvidar los <a href="http://es.rsf.org/estados-unidos-acusado-de-ser-un-hacker-el-11-07-2013,44926.html">105 años de prisión a los que podría ser condenado el joven periodista independiente Barrett Brown</a> por haber compartido en línea correos electrónicos de la compañía privada de inteligencia y espionaje Stratfor, contratada por el gobierno.
</p><p>
Por su parte, el Reino Unido (33°, -3) destacó por las escandalosas presiones que ejerció sobre el diario <i>The Guardian </i>y por la detención durante nueve horas de David Miranda, compañero y colaborador del periodista Glenn Greenwald, llevadas a cabo en nombre de la lucha contra el terrorismo. Las autoridades de los dos países parecen esforzarse más en perseguir a los informantes que en regular prácticas de vigilancia abusivas que constituyen negaciones al principio de <i>privacy</i>, tan preciado para su cultura democrática.
</p><p>
La ley sobre “los secretos de Estado” adoptada por la Dieta nipona (Parlamento de Japón) a finales de 2013, hace más opaca la gestión del gobierno japonés de temas de interés general, como los relativos a lo nuclear o a la relación con Estados Unidos, convertidos en tantos de los “grandes tabús”. Las nociones de “periodismo de investigación”, “interés público” y “secreto de fuentes” pasaron como pérdidas y ganancias de los diputados, muy preocupados por evitar que la imagen del país (59º, -5) se vea afectada por información comprometedora.
</p><p>
La “lucha contra el terrorismo” es instrumentalizada por gobiernos prontos a calificar a los periodistas de “amenazas a la seguridad nacional”. Decenas de periodistas fueron encarcelados con ese pretexto en Turquía (154°, +1), en especial cuando cubrían la cuestión kurda. Marruecos, donde las autoridades confunden de buena gana “periodismo” y “terrorismo” desde el caso Ali Anouzla, se estanca en el lugar 136. En Israel (96°, +17) la libertad de información es una noción vulnerable frente al argumento de la seguridad nacional. En el Cachemira indio los servicios de Internet móvil y las comunicaciones se suspenden en cuanto existen amenazas de disturbios. En el norte de Sri Lanka (165°, -2) reina el ejército, que no tolera ningún esguince en la visión oficial del proceso de “pacificación” de los antiguos bastiones separatistas tamiles. Amedrentados por los sobresaltos de las “primaveras árabes”, los países de la Península Arábiga, así como los regímenes autoritarios de Asia Central, refuerzan la censura y la vigilancia de los medios de comunicación, pendientes de todo “intento de desestabilización del poder”.
</p>
<div>
<h5>PRIVATIZACIÓN DE LA VIOLENCIA</h5>
<p>Los grupos infraestatales constituyen en algunos países la principal causa de inseguridad para los periodistas. Las milicias que mantienen el caos en la nueva Libia (137e, -5) o los grupos armados yemenitas ligados a Al Qaeda en la Península Arábiga son los rostros de esta privatización de la violencia. Las milicias Al Shabab en Somalia (176°, 0) o el movimiento M23 en la República Democrática del Congo (151°, -8) tienen en común que consideran a los periodistas como enemigos. Los grupos yihadistas como Jabhat Al Nusra y el Estado Islámico de Irak y Levante (ISIS), deseosos de controlar las zonas que “liberan”, agreden violentamente a los actores de la información.
</p><p>
Por otro parte y de manera más global, el crimen organizado sigue siendo una temible fuerza predadora. Es el caso de Honduras (129°, -1), Guatemala (125°, -29), Brasil (111°, -2) y Paraguay (105 °, -13), pero también de Paquistán, China, Kirguistán y los Balcanes. A la sombra de esta mano criminal es difícil, por no decir imposible, evitar la autocensura en torno a temas tan delicados como la corrupción, el narcotráfico o la infiltración de las mafias en los engranajes del Estado. La pasividad, incluso la complicidad o la complacencia, de ciertas autoridades –en ocasiones implicadas directa o indirectamente en crímenes contra medios de comunicación– acentúa la impunidad de la que gozan estos cárteles criminales y nutre el ciclo de violencia que golpea a los actores de la información.
</p><p>
El índice anual de la libertad de prensa, establecido por primera vez en la Clasificación de 2013, confirma que existe una degradación a escala mundial de la situación del derecho de informar y de ser informado. El índice pasa de 3 395 a 3 456 (+61), es decir, experimenta un aumento de 1,8%, lo que revela una ligera degradación global de la libertad de información entre la edición 2013 y la 2014 de la Clasificación Mundial.
</p><p>
Si bien el año 2013 fue menos mortífero para los periodistas que el precedente, marcado por una hecatombe para el gremio, las agresiones y las amenazas fueron más numerosas. El alza del índice se explica por la evolución no sólo de las exacciones, sino también del conjunto de indicadores empleados para establecer la clasificación:
</p><p>
— el pluralismo, es decir, la representación de las diferentes opiniones en los medios de comunicación;
— la independencia de los medios de comunicación respecto a los diferentes poderes: político, económico, religioso y militar;
— la calidad del marco legal que regula las actividades informativas;
— la transparencia de las instituciones que rigen estas actividades;
— el desempeño de la infraestructura que las sostiene;
— el clima general en que se ejerce la libertad de informar.
</p><p>
Este índice es una herramienta analítica del desempeño global de los países estudiados. Es un hecho irrefutable: en su enfoque regional, el índice muestra que la situación se degrada en todos los continentes, con excepción de Asia, donde el índice es estable. La zona de la Unión Europea y los Balcanes obtiene la mejor calificación (17,6), le siguen, como el año pasado, las zonas: América (30,3), África (35,6), Asia-Pacífico (42,2) y Europa del Este y Asia Central (45,5). La zona África del Norte y Oriente Medio es la última de la lista con un índice de 48,7.
</p><p>
<b>Índice anual de la libertad de prensa</b>: 3 456 en 2014 (3 395 en 2013)
<ul>
	<li>Unión Europea y los Balcanes:17,6 (17,5)</li>
	<li>América: 30,3 (30,0)</li>
	<li>África: 35,6 (34,3)</li>
	<li>Asia-Pacífico: 42,2 (42,2)</li>
	<li>Europa del Este y Asia Central: 45,5 (45,3)</li>
	<li>África del Norte y Oriente Medio: 48,7 (48,5)</li>
</ul>
</p>
</div>
<h5>GRANDES CAÍDAS</h5>
<p>En el continente americano, además del descenso de trece lugares experimentado por Estados Unidos (46°, -13), Guatemala (125°, -29) también vivió una caída vertiginosa debido a la agravación de la inseguridad de los periodistas: se duplicó el número de agresiones respecto al año pasado y hubo <a href="http://es.rsf.org/guatemala-prosigue-la-serie-negra-cuarto-20-08-2013,45079.html">cuatro asesinatos</a>. Una tendencia similar se registró en Paraguay (105°, -13), donde los periodistas, de por sí obligados a la autocensura, no dejan de sufrir presiones. Además, un <a href="http://es.rsf.org/paraguay-asesinan-a-un-periodista-la-26-04-2013,44434.html">profesional de los medios de comunicación fue asesinado</a> en 2013. El país ya había sufrido una fuerte caída tras el golpe parlamentario que derrocó al presidente Fernando Lugo en junio de 2012, el cual ocurrió tres años después del golpe de Estado que hizo literalmente hundirse a Honduras (129°, -1), ahora atascado en el caos poselectoral.
</p><p>
En el continente africano las dos caídas más notables, la de Malí y la República Centroafricana, se debieron a los conflictos armados, como se mencionaba anteriormente. En Burundi, mientras que la campaña presidencial se perfila, el Senado votó una ley que restringe las libertades de los periodistas. En Kenia (90°, -18), la respuesta autoritaria de las autoridades a la cobertura mediática del atentado de Westgate, que fue muy criticada, se suma a iniciativas parlamentarias peligrosas –en primer lugar, la ley adoptada a finales de 2013 que crea un tribunal especial para juzgar los contenidos audiovisuales.
</p><p>
En Guinea (102°, -15), en un contexto poselectoral marcado por numerosas protestas, los periodistas se vieron atrapados entre la represión gubernamental y las manifestaciones exacerbadas, lo que volvió peligrosas y difíciles sus condiciones de trabajo. Varios periodistas fueron heridos y agredidos durante las manifestaciones.
</p><p>
Las medidas de censura y bloqueo contra sitios informativos en Zambia (93°, -20) perjudicaron la evaluación del país, que había progresado en años precedentes.
</p><p>
Finalmente, en países donde los dirigentes que están en el poder desde hace mucho tiempo temen los cambios de régimen, presenciamos el tradicional endurecimiento de las políticas contra los actores de la libertad de información: procesos judiciales abusivos en Chad (139°, -17), múltiples suspensiones de medios de comunicación en Camerún (131°, -10).
</p><p>
Kuwait (91°) sufrió una caída de 13 lugares que refleja un cierto endurecimiento y se explica en parte por la adopción de una Ley de Medios de Comunicación que permite a las autoridades condenar a los periodistas a pagar multas que pueden llegar hasta los 300.000 dinares (cerca de un millón de dólares) por “criticar al emir o al príncipe heredero” o por “deformación de su discurso”. El texto también prevé penas que pueden llegar hasta los diez años de prisión para los periodistas que ofendan a Dios, a los profetas del Islam o a los compañeros y las esposas del profeta Mahoma.
</p><p>
Estas espectaculares evoluciones no deben hacer olvidar el trágico estancamiento observado en la parte inferior de la clasificación: año tras año Vietnam (173°, -1), Uzbekistán (166°, -1) y Arabia Saudita (164°, 0), por citar sólo algunos ejemplos, no dejan de intensificar su control de la información y saben adaptar sus métodos de censura radical a la era digital. A aquellos que tienen el valor de resistirlos les tienen destinados los castigos más crueles. En Kazajistán (161°, 0) y en Azerbaiyán (160°, -3) el pluralismo de los medios de comunicación está a punto de sucumbir ante la línea represiva de dirigentes inamovibles.
</p><p>
<h5>MEJORAS NOTABLES EN LA EDICIÓN 2014 DE LA CLASIFICACIÓN</h5>
<p>Los casos de violencia, censura directa y abusos en el uso de procesos legales tendieron a disminuir en Panamá (87°, +25), República Dominicana (68°, +13), Bolivia (94°, +16) y Ecuador (94°, +25). No obstante, en este país el grado de polarización no ha disminuido mucho y sigue perjudicando el debate público.
</p><p>
El año 2013 estuvo marcado por algunos avances legislativos dignos de alabanza. Por ejemplo, en África del Sur (42°, +11) el presidente se negó a firmar una ley considerada liberticida por los medios de comunicación.
</p><p>
En Georgia (84°, +17), la elección presidencial de 2013 se desarrolló en medio de un clima menos tenso respecto al de las elecciones legislativas del año precedente, marcadas por numerosas agresiones y campañas de odio contra periodistas. A favor de la cohabitación política y, después, de la alternancia, el país recupera parte del terreno perdido en estos últimos años, mientras que el impulso reformador del gobierno de Mikheil Saakachvili se debilita. Sin embargo, la fuerte polarización del paisaje mediático representa aún un gran desafío para el futuro.
</p><p>
Israel gana 17 lugares. Las consecuencias de la Operación Pilar Defensivo, efectuada en noviembre de 2012, por la que dos periodistas perdieron la vida, fueron tomadas en cuenta en la clasificación de 2013, así como las numerosas redadas emprendidas contra medios de comunicación palestinos, que entonces le hicieron perder 20 lugares en la clasificación. Así que esta mejora es relativa. La libertad de información sigue supeditada al argumento de la seguridad nacional. Si bien la prensa israelí goza de libertad para expresarse, los medios de comunicación ubicados en “territorio israelí” (según la concepción israelita) deben sortear la censura militar previa y las “gag orders” (órdenes de censura). No son bienvenidas las investigaciones sobre temas delicados, relacionadas con la seguridad nacional. Las exacciones del ejército israelí contra los profesionales de la información palestinos y extranjeros siguen siendo muy frecuentes, en especial durante las manifestaciones semanales frente al muro de separación. En noviembre de 2013 numerosos fotoperiodistas fueron tomados como blanco deliberadamente cuando se retiraban del lugar donde se realizaba la manifestación. La Suprema Corte de Justicia aprobó el 4 de diciembre pasado la orden de confiscar el equipo de <i>Wattan TV</i>; el decomiso se había llevado a cabo en febrero de 2012, durante una redada del ejército.
</p><p>
Timor Leste (77°) gana 14 lugares después de un congreso histórico de periodistas que tuvo lugar en Dili del 25 al 27 de octubre, durante el cual fue aprobado el primer código deontológico y un Consejo de Prensa, conformado por siete miembros. La vigilancia permanece. La Ley de Prensa que actualmente se estudia en el Parlamento constituye el próximo gran reto para la libertad de los medios de comunicación en el país.
</p>
<h5>¿MODELOS REGIONALES A LA DERIVA?</h5>
<p>La evolución de algunos países en la clasificación, sintomática de su enfoque de la libertad de información, no sólo impacta a su población, también a los países vecinos, debido a su proyección regional o a su influencia en otros Estados que los miran –con o sin razón– como modelos, ejemplos a observar o a seguir.
</p><p>
La mejora constatada en Sudáfrica (42°, +11) va a contracorriente respecto a otros países que se muestran como modelos regionales, por fuerza estancados o en regresión.
</p><p>
Acelerada por los efectos de la crisis económica y los accesos de fiebre populistas, la dispersión de los países de la Unión Europea en la clasificación continúa. Es particularmente el caso de Grecia (99°, -14) y de Hungría (64°, -7). En Grecia, los periodistas a menudo son agredidos por miembros de Amanecer Dorado, partido neonazi que entró al Parlamento en junio de 2012. El Estado griego también tiene una gran parte de responsabilidad: cerrando el grupo audiovisual público griego bajo la presión de la troika (Comisión Europea, Banco Central Europeo, Fondo Monetario Internacional), el gobierno de Antonis Samaras parece haberse ahorrado también democracia. En Hungría, el gobierno de Viktor Orbán da la impresión de haber perdido los valores democráticos de la Unión Europea y encadena reformas liberticidas. Consecuencia directa de la erosión del modelo europeo, la Unión tiene cada vez más dificultad para jalar hacia arriba a los países candidatos: las negociaciones de adhesión no siempre se traducen en los esfuerzos esperados en el plano de las libertades públicas. Por ejemplo, Macedonia, país que se encuentra en el lugar 123, nunca había estado tan mal clasificado.
</p><p>
Los gigantes del Nuevo Mundo, Estados Unidos (46°, -13) y Brasil (111°, -2), tampoco ponen el ejemplo. El primero se desgarra desde el 11 de septiembre de 2001 por el dilema de los imperativos de la seguridad nacional y el respeto de los principios de la primera enmienda. El segundo, es uno de los países más mortíferos del continente para la prensa; la inseguridad se mantiene por las mafias y el crimen organizado. El “país de los treinta Berlusconi” está discapacitado por un modelo mediático que obstaculiza el pluralismo.
</p><p>
Si bien Rusia (148°, +1) no se hunde más en la clasificación, sólo se lo debe a la resistencia y la perseverancia de su sociedad civil. En realidad, las autoridades intensifican cada día su política represiva, emprendida desde que Vladimir Putin regresó al Kremlin, en 2012. Asimismo, exportan este modelo a través de toda la ex Unión Soviética. De Azerbaiyán (160°, -3) a Asia Central, pasando por Ucrania (127°, 0), las legislaciones liberticidas y los sistemas de vigilancia de las comunicaciones rusas se multiplican alegremente. Moscú también utiliza las instancias de la ONU y las alianzas regionales, como la Organización de Cooperación de Shanghai, para socavar los estándares internacionales en materia de libertad de información.
</p><p>
En el lugar 154, lejos de sus aspiraciones regionales, Turquía no registra ninguna mejora y sigue siendo una de las mayores prisiones del mundo para los periodistas. La revuelta de Gezi sacó a la luz las prácticas represivas de las fuerzas del orden, el avance de la autocensura y los peligros del discurso populista del Primer Ministro. Los plazos electorales y los desconocidos del proceso de paz con la rebelión kurda anuncian desde ahora un año 2014 determinante para el futuro de las libertades públicas.
</p><p>
En China (175°, -1) existe una blogósfera de una vitalidad sorprendente y que cada vez se moviliza más. Este país sigue censurando y encarcelando a las voces disidentes, por lo que retrocede aún un lugar. La nueva potencia utiliza su peso económico para ampliar su influencia en los medios de comunicación de Hong Kong, Macao y Taiwán y volver a cuestionar su independencia.
</p><p>
India (140°, +1) fue golpeada por una ola de violencia contra los actores de información sin precedentes. Ocho profesionales de los medios de comunicación fueron asesinados en 2013. Los periodistas con frecuencia son el blanco de diversos actores, del Estado y ajenos a él. Ninguna región –o casi– se encuentra exenta, incluso si Cachemira y Chhattisgarh siguen siendo los únicos dos estados donde la violencia y la censura son endémicas. Los grupos mafiosos, los manifestantes y los militantes políticos, así como la policía y las fuerzas de seguridad locales, son responsables de amenazas y de actos de violencia física contra periodistas, quienes muy a menudo se ven abandonados por la justicia y obligados a la autocensura.
</p><p>
La excepcional apertura de Birmania, que podría erigirse como un modelo de transición democrática en la región, se tradujo en un fuerte progreso del país en la clasificación de 2013. Mientras que el proceso de reformas se agota, el “modelo birmano” aún debe superar algunas pruebas.
</p>
</div></div>

<?php include "es-footer.php" ?>