<?php 
	$selected 	= "mo";
	$title 		= "World Press Freedom Index 2014 | EASTERN EUROPE AND CENTRAL ASIA"
?>
<?php include "es-header.php" ?>

<h2>África del Norte y Oriente Medio</h2>
<h5>UNA CRISIS SIRIA CON GRANDES CONSECUENCIAS PARA LA LIBERTAD DE INFORMACIÓN EN ORIENTE MEDIO</h5>
<p>
<strong>Siria</strong> es <a href="http://en.rsf.org/syrie-journalism-in-syria-impossible-job-06-11-2013,45424.html">el país más peligroso del mundo para los periodistas</a>. El año 2013 estuvo marcado porque: el conflicto se volvió aún más complejo y la situación de seguridad sufrió un fuerte deterioro. Desde marzo de 2011 han sido asesinados más de 110 actores de información. Estos se encuentran entre la espada y la pared: por un lado, el ejército de Bachar el Asad, que continúa deteniendo y asesinando a los testigos incómodos que dan cuenta del conflicto; por otro, grupos islamistas armados en las zonas llamadas “liberadas” del norte del país, principalmente el Estado Islámico de Irak y el Levante (Islamic State of Iraq and Sham, ISIS). Desde la primavera de 2013 estos grupos han multiplicado los secuestros y creado comités jurídicos (<i>hay’at shar’iya</i>) caracterizados por la arbitrariedad. En las zonas kurdas, las fuerzas de seguridad del Partido de la Unión Democrática (PYD), la principal fuerza política, constituyen un obstáculo para el ejercicio de la libertad de información. Amenazados por todas partes, los actores de la información sirios huyen masivamente del país.
</p><p>
En <strong>Líbano</strong>, donde los medios de comunicación son herramientas de propaganda al servicio de empresarios y políticos, el conflicto sirio consolida la línea de fractura ya existente entre los medios de comunicación de la coalición “8 de marzo” (principal movimiento chiita, apoyado por Irán y el régimen de Damasco) y los de la alianza “14 de marzo” (principal movimiento sunita, apoyado por Arabia Saudita, contra el régimen de Damasco). Esta extrema polarización entre medios de comunicación “pro gobierno de Damasco” y “pro oposición” refuerza la polarización sociopolítica de la sociedad libanesa.
</p><p>
Las “primaveras árabes” y los acontecimientos en Siria han llevado a las autoridades de <strong>Jordania</strong> a reforzar su control de los medios de comunicación, en especial en Internet, a riesgo de suscitar una protesta entre la sociedad civil jordana. <a href="http://en.rsf.org/jordan-letter-to-king-abdullah-about-18-06-2013,44791.html">En junio de 2013 cerca de 300 sitios web informativos fueron bloqueados en territorio jordano</a>, en aplicación de una nueva ley de prensa que restringe drásticamente la libertad de información en línea.
</p><p>
Desde 2012 <strong>Irak</strong> se sumerge en un nuevo ciclo de violencia, sobresaltos de la guerra civil engendrada por la intervención estadounidense de 2003 y el caos en el que ésta hundió al país. Las tensiones religiosas entre sunitas y chiitas se exacerban por el conflicto sirio e impactan negativamente la seguridad de los periodistas y la independencia de los medios de comunicación, quienes también se ven afectados por los bloqueos cotidianos efectuados por las autoridades y las fuerzas de seguridad.<em><strong>
</strong></em>
</p><p>
<strong>Irán</strong>, actor regional indudable, juega un papel crucial en el conflicto sirio. Las autoridades continúan controlando estrictamente la información, en especial cuando ésta tiene que ver con Damasco (su aliado), con la presencia de los Guardianes de la Revolución o con las ayudas financieras; tantos temas que se considera “ponen en peligro la seguridad nacional”. También se censura la cuestión nuclear, la situación de los derechos humanos y de los presos políticos. A finales de 2013 Irán seguía siendo una de las mayores prisiones del mundo para los profesionales de los medios de comunicación con 50 periodistas y netciudadanos encarcelados. Pese a que algunos presos de opinión fueron puestos en libertad, las promesas del candidato Hassan Rohani de “liberar a todos los presos políticos” y de un cambio “a favor de la libertad de expresión y de prensa” son letra muerta desde que llegó al poder.
</p>
<h6>Siria</h6>
<p>Según Reporteros sin Fronteras, entre marzo de 2011 y diciembre de 2013:
</p><p>
— cerca de 130 actores de la información fueron asesinados mientras realizaban su labor; 25 de ellos eran periodistas profesionales, de los cuales siete eran extranjeros;
— más de 120 actores sirios de la información han huido del país.
A finales de 2013:
</p><p>
— cerca de veinte actores de la información sirios se encuentran detenidos por el régimen de Bachar el Asad;
— 19 periodistas extranjeros están detenidos, retenidos como rehenes o se encuentran desaparecidos;
— más de 20 actores de la información sirios están retenidos como rehenes por grupos armados islamistas.
</p>
<h5>CUANDO GRUPOS INFRAESTATALES SIN LEGITIMIDAD HACEN QUE REINE EL MIEDO</h5>
<p>En algunos países los grupos infraestatales constituyen la amenaza principal para los actores de la información y son fuente inseguridad. En <strong>Siria</strong>, los nuevos predadores de la libertad de información son los grupos islamistas armados, que multiplican los secuestros y las amenazas desde la primavera de 2013. En <strong>Irak</strong> las milicias armadas, con frecuencia ligadas a organizaciones político-religiosas, no dudan en agredir a periodistas.
</p><p>
En <strong>Libia</strong>, la libertad de información se encuentra amenazada por la inseguridad rampante que continúa sacudiendo al país. La revolución del 17 de febrero de 2011 condujo al derrocamiento de Muamar el Gadafi, tras más de cuarenta años de un poder absoluto que se apoyaba en un estricto control de la información. Tres años más tarde, ser periodista en Libia sigue siendo una tarea particularmente ardua. El impulso generado por la “primavera de los medios de comunicación” se debilita. La Libia “libre” dirigida por un gobierno de transición se caracteriza hoy por un estado cercano a la anarquía donde el reino de las milicias armadas prevalece sobre el Estado de Derecho. Los profesionales de los medios de comunicación se encuentran muy afectados por ello: autocensura persistente, repetidas amenazas, intimidaciones, detenciones arbitrarias, incluso tortura. Ya sean grupos armados sumariamente, estructuras <i>ad hoc </i>legitimadas por el gobierno –como algunos de los doce “Escudos de Libia”, milicia bajo la autoridad del Ministerio de Defensa libio–, o famosas milicias como Al-Qa’qa’a, todos fueron responsables de exacciones a periodistas.
</p><p>
Los ciudadanos <strong>yemenitas</strong> gozan de una mayor libertad de expresión desde que Abd Rabbuh Mansur al Hadi sucedió a Ali Abdullah Saleh en la presidencia, en febrero de 2012. Sin embargo, diversos grupos armados son responsables de un <a href="http://www.hrw.org/reports/2013/09/19/life-threatening-career">recrudecimiento de la violencia y de las amenazas contra medios de comunicación</a>. Estén ligados a Al Qaeda en la Península Arábiga, a la rebelión houthi en el norte, al movimiento secesionista en el sur o a conservadores religiosos, todos agreden a los actores de la información. Los partidos políticos también tienen un rol: la mayoría de los medios de comunicación yemenitas forman parte de organizaciones políticas de las que son portavoces. Por si esto fuera poco, además de ser el blanco de actores que no pertenecen al Estado, numerosos periodistas enfrentan la desconfianza, incluso la hostilidad, de las fuerzas de seguridad. La <a href="http://www.freedomfoundation-yemen.org/en/">ONG yemenita Freedom Foundation</a> –que vigila la situación de los medios de comunicación en el país– registró en el primer semestre de 2013, 144 ataques que afectaron a 205 personas. En el momento álgido de la revuelta en 2011, el Sindicato de Periodistas Yemenitas registró 333 ataques a periodistas y medios de comunicación. Existe impunidad: la justicia fracasó ampliamente en abrir investigaciones por estos casos de exacciones y sancionar a los responsables. Pese a la apertura de un “diálogo nacional”, la Ley de Prensa y Publicaciones aún no ha sido modificada: siguen a la orden del día los tribunales de excepción y las penas de privación de la libertad para los periodistas.
</p>
<h6>Doble pena para los periodistas iraquíes</h6>
<p>
En <strong>Irak</strong> los grupos armados no dudan en agredir a los periodistas. A finales de 2013, en espacio de dos meses, cuatro reporteros fueron asesinados en Mosul. En noviembre de 2013 dos camarógrafos, <a href="http://en.rsf.org/iraq-journalist-gunned-down-in-mosul-25-11-2013,45508.html">‘Alaa Edward Boutros</a>, del canal local de TV <em>Nineveh Al-Ghad</em>, y <a href="http://en.rsf.org/iraq-journalist-gunned-down-in-mosul-25-10-2013,45378.html">Bachar Abdulqader Najm Al-Nouaïmi</a>, de la cadena <em>Al-Mosuliya</em>, fueron asesinados. Semanas antes, <a href="http://en.rsf.org/iraq-killing-of-two-tv-journalists-07-10-2013,45293.html">el corresponsal de la cadena <em>Al-Sharqiya TV</em>, Mohamed Karim Al-Badrani</a>, y su camarógrafo, Mohamed Al-Ghanem, sucumbieron bajo las balas de desconocidos. La impunidad reina. Ninguno de los asesinos ha sido detenido. En lugar de tomar las medidas necesarias para garantizar la protección de los actores de información iraquíes, las autoridades contribuyen al clima de inseguridad que afecta a los periodistas culpándolos por los textos que escriben.
</p><p>
<strong>LOS HERMANOS MUSULMANES Y LA LIBERTAD DE INFORMACIÓN</strong>
</p><p>
<strong><a href="http://en.rsf.org/egypt-mounting-freedom-of-information-27-06-2013,44862.html">Egipto bajo el poder de Morsi o la “hermanización” de los medios de comunicación</a></strong>
</p><p>
<strong></strong>En <strong>Egipto</strong>, la caída de Hosni Mubarak en febrero de 2011 alimentó las esperanzas de que la situación de las libertades fundamentales mejoraría. La llegada al poder de los Hermanos Musulmanes en el verano de 2012 acabó rápidamente con estas esperanzas. En noviembre de 2012 el presidente Morsi hizo que se adoptara un decreto constitucional que ampliaba sus poderes y luego dio marcha atrás debido a una oposición generalizada. La Constitución adoptada a finales de 2012 por referéndum no ofrece suficientes garantías en materia de libertad de expresión. De hecho, la independencia de los medios de comunicación públicos no está garantizada. La ley fundamental abre en realidad la vía a una islamización del marco legal. Una vez en el poder, les Hermanos Musulmanes se esforzaron por controlar los medios de comunicación públicos. En agosto de 2012 Mohamed Morsi hizo que la Cámara Alta del Parlamento nombrara a personas cercanas a la hermandad como <a href="http://en.rsf.org/egypt-newspaper-editor-detained-muslim-23-08-2012,43268.html">responsables de las publicaciones de prensa gubernamentales</a>. Estas designaciones influyeron ampliamente en la línea editorial de estos medios de comunicación. Las denuncias contra los periodistas y las agresiones estallaron.
<h6>Una “sisización” de los medios de comunicación egipcios, desde julio de 2013</h6>
<p>Después de que el ejército tomó el poder, las nuevas autoridades egipcias, comandadas por el general Al Sisi, agredieron sistemáticamente a los medios de comunicación extranjeros, así como a los medios de comunicación de los Hermanos Musulmanes, o considerados cercanos a ellos, que de nuevo padecieron la censura. En el segundo semestre de 2013 cinco reporteros fueron asesinados y al menos 80 periodistas fueron interpelados arbitrariamente por la policía o por los manifestantes, a favor de Morsi o del ejército. Las detenciones arbitrarias y la tortura se generalizaron. La “<a href="http://en.rsf.org/egypte-egyptian-authorities-to-put-20-al-30-01-2014,45803.html">caza a los Hermanos</a>” toma como blanco a los periodistas egipcios, pero también a sus colegas turcos, palestinos y sirios, lo que no concuerda con ciertas decisiones tomadas por el comité encargado de la redacción de la nueva Constitución egipcia, que votó un artículo que prohibía la detención de los profesionales de la información.
</p>
<h6>La coartada marroquí de la lucha contra el terrorismo</h6>
<p>Las autoridades marroquíes, bajo la batuta de los islamistas desde las elecciones de 2011, tardan en concretar las promesas de reformas anunciadas desde el referéndum constitucional de 2011. El año 2013 estuvo marcado por el “<a href="http://en.rsf.org/morocco-letter-to-john-kerry-about-freedom-08-11-2013,45430.html">caso Ali Anouzla</a>”. El director del portal informativo <i>Lakome</i> en lengua árabe fue detenido en septiembre por haber publicado un enlace que dirigía a una nota del diario español <i>El País, </i>que a su vez contenía un enlace a un<i> </i>video atribuido a Al Qaeda en el Magreb Islámico (AQMI). Tras cinco semanas en detención, fue puesto en libertad. El periodista estaba acusado de “apoyo material e incitación directa a cometer actos terroristas”, por lo que corría el riesgo de enfrentar una pena de entre diez y treinta años de prisión. Este caso ilustra la preocupante amalgama que hacen las autoridades marroquíes entre trabajo periodístico e incitación a la ejecución de actos terroristas.
</p>
<h6>Túnez: nombramientos que condenan la independencia de los medios de comunicación públicos</h6>
<p>El ascenso al poder del partido Ennahda tras las primeras elecciones libres de Túnez no permitió romper con el –tradicional– control que ejercen las autoridades sobre los medios de comunicación públicos. Además, retomando las costumbres del sistema de Ben Ali, el partido islamista emprendió el juego de las sillas, haciendo y deshaciendo las carreras profesionales, con las personas a la cabeza de las radios y televisiones públicas. El 3 de mayo de 2013 el n<a href="http://en.rsf.org/tunisia-government-finally-appoints-07-05-2013,44580.html">ombramiento de los miembros de la Alta Autoridad Independiente para la Comunicación Audiovisual (HAICA)</a> hizo renacer las esperanzas de los defensores de la libertad de prensa. Esperanzas que rápidamente se perdieron con una inesperada ola de nombramientos en los puestos clave del sector audiovisual público, en agosto del mismo año. Tres años después de la caída de Zine el Abidine Ben Ali, la mano de hierro del político sigue haciendo corto circuito con los intentos de reforma, haciendo imposible la independencia de los medios de comunicación públicos.
</p>
<h5>PÉNINSULA ARÁBIGA: EL CONTROL DE LA INFORMACIÓN, UNA PRIORIDAD</h5>
<p>Los países de la península arábiga, escaldados por los riesgos de contagio de las “primaveras árabes”, refuerzan su vigilancia y control de los medios de comunicación, comenzando por Internet, que se ha convertido en el lugar de expresión de una libertad que no logra hacerse sitio en los medios de comunicación tradicionales. Los ciberpolicías de las monarquías del Golfo Pérsico también están a la caza de todo texto, boletín o tweet crítico que cuestione la gestión política actual.
</p><p>
En los <strong>Emiratos Árabes Unidos</strong> se reprime toda cercanía a los Hermanos Musulmanes. <a href="http://en.rsf.org/united-arab-emirates-three-netizens-still-held-for-08-09-2013,45149.html">Dos netciudadanos que difundieron en Twitter</a> información sobre el proceso de 94 emiratíes acusados de ser parte del partido Al-Islah fueron condenados a largas penas de prisión. Las autoridades habían decidido <a href="http://en.rsf.org/united-arab-emirates-news-blackout-imposed-on-trial-of-25-03-2013,44256.html">prohibir el acceso al tribunal</a> a los observadores y a la prensa internacional, dejando sólo a periodistas locales, cuidadosamente seleccionados, cubrir las audiencias. Un escenario similar se perfila para el proceso de los veinte egipcios y diez emiratíes acusados de mantener nexos con los Hermanos Musulmanes y haber intentado derrocar al régimen, un proceso abierto en noviembre de 2013. Podríamos apostar que Twitter será examinado con lupa y que las autoridades no dudarán en sancionar severamente a quienes se atrevan a romper la ley del silencio.
</p><p>
<strong>Arabia Saudita</strong>, que se encuentra en la lista de países “<a href="http://en.rsf.org/saudi-arabia-12-03-2012,42052.html">Enemigos de Internet</a>” de Reporteros sin Fronteras, no se queda atrás. El reino aplica una censura implacable a sus propios medios de comunicación y a Internet, multiplicando las condenas a netciudadanos. En 2013 los censores siguieron muy de cerca las reivindicaciones a favor del derecho de conducir de las mujeres, un tema muy popular en la Web y que tuvo cierto eco en los medios de comunicación tradicionales. Así, a finales de octubre de 2013, <a href="http://en.rsf.org/saudi-arabia-saudi-journalist-detained-over-31-10-2013,45408.html">Tariq al Mubarak, articulista de <i>Asharq al-Awsat</i></a>, fue detenido por haber publicado –entre otros– un artículo en el que criticaba la prohibición de conducir impuesta a las mujeres saudíes. Cuando se trata de religión, las autoridades de Riyad bromean aún menos. A fines de julio de 2013 se condenó en primera instancia al fundador del sitio web Liberales saudíes (censurado desde entonces) a siete años de prisión y a recibir 600 latigazos. <a href="http://en.rsf.org/saudi-arabia-seven-years-in-jail-and-600-lashes-06-08-2013,45021.html">Raef Badawi</a> publicó un artículo sobre el día de San Valentín que denigraba a la policía religiosa. Cuando se abrió su proceso, en junio de 2012, fue juzgado inicialmente por “<a href="https://ifex.org/saudi_arabia/2013/07/31/liberal_blogger/">apostasía</a>” (abandono o negación de las creencias de la religión), cargo que finalmente fue retirado.
</p><p>
En <strong>Kuwait</strong> las autoridades dan una vuelta de tuerca en lo que se refiere a los dos principales temas delicados: la persona del emir y la religión. <a href="http://en.rsf.org/kuwait-journalists-could-be-fined-a-10-04-2013,44363.html">Dos periodistas ciudadanos</a>, Badr al Rashidi y Ourance al Rashidi, fueron condenados por “insulto al emir”. El perdón sigue dependiendo del príncipe; en julio de 2013 fueron agraciados por él. Si la ley no se reforma, aún se puede caer en ese tipo de condenas. En abril de ese mismo año se abandonó un proyecto de ley liberticida, que contemplaba multas que podían llegar hasta unos 800.000 euros por “crítica al emir o al príncipe heredero” y penas de hasta diez años de prisión por “ofensa a Dios, a los profetas del Islam o a los compañeros y las esposas del profeta Mahoma”.
</p><p>
Finalmente, en <strong>Omán</strong>, la persona del sultán sigue siendo uno de los principales tabús. <a href="http://en.rsf.org/oman-sultan-qaboos-pardons-all-22-03-2013,44251.html">Quien lo critique se expone a la ira del poder.</a> Algunos lo han pagado caro antes de ser indultados.
</p>
<h6>Bahréin, reino de la desinformación</h6>
<p>Desde el inicio de la revuelta popular, en febrero de 2011, las autoridades de Bahréin se volvieron <a href="http://en.rsf.org/bahrain-don-t-leave-news-out-of-the-race-18-04-2013,44388.html">maestras en el arte de manipular la información sobre las manifestaciones y su represión</a>. Preocupadas por su imagen, supieron manejar hábilmente a las potencias occidentales, reticentes a condenar las exacciones cometidas en el país, que se contentaron con los efectos de anuncio de los dirigentes bahreiníes y con reformas superficiales. Así, Manama fue elegida como capital de la cultura árabe en 2012 y capital del turismo árabe en 2013. Último golpe maestro de estos ases de la comunicación: <a href="http://en.rsf.org/bahrain-five-news-providers-currently-03-09-2013,45134.html">Bahréin acogerá el Tribunal Árabe de los Derechos Humanos de la Liga Árabe</a>… a pesar de que ciertas prisiones del reino rebosan de presos de conciencia.
</p>
<?php include "es-footer.php" ?>