<?php 
	$selected 	= "ameriques";
	$title 		= "Classement de la liberté de la presse 2014 | AFRIQUE"
?>
<?php include "fr-header.php" ?>

	<h2>Amériques</h2>
	<h5>L’INFORMATION À L’ÉPREUVE D’UNE VIOLENCE MULTIPLE</h5>
	<div>
<p>
	Plus de vingt ans ont passé depuis que l’Amérique latine et les Caraïbes ont presque cessé de vivre sous la botte des dictatures militaires ou sous le feu des guerres civiles. La <a href="http://fr.rsf.org/colombie.html" target="_blank">Colombie</a> fait exception avec un conflit armé vieux d’un demi-siècle. <a href="http://fr.rsf.org/cuba.html" target="_blank">Cuba</a> se distingue également par son régime hérité de la guerre froide, qui ne tolère aucun contre-pouvoir indépendant, mais voit à son tour l’émergence d’une société civile forcer la remise en cause de son « modèle ». État de paix et institutions démocratiques ont formellement gagné. Formellement, car il reste du chemin à parcourir entre la garantie constitutionnelle des libertés publiques et un réel État de droit. Nombreux sont les journalistes et défenseurs des droits de l’homme à l’éprouver tous les jours face à une violence à la fois élevée et multiple, mêlant crime organisé, paramilitarisme et parfois répression d’État.
</p><p>
	Exemplaire de cette sanglante confluence, le <a href="http://fr.rsf.org/honduras.html" target="_blank">Honduras</a> affiche un taux d’homicide proche de celui d’un pays en guerre, avec une moyenne de 80 pour 100 000 habitants (le pays n’en comptant au total que sept millions). Une trentaine de journalistes y ont été tués en une décennie dont vingt-sept <a href="http://fr.rsf.org/honduras-les-medias-dans-la-tourmente-du-07-09-2009,33693.html" target="_blank">à la suite du coup d’État</a> qui renversa le président élu Manuel Zelaya le 28 juin 2009. Le lien avec l’activité professionnelle est établi pour neuf de ces affaires, l’impunité quasi absolue constituant la règle dans cet État failli. Attentats, menaces, agressions et « sanctuarisations » de certains médias doivent autant à des milices privées à la solde des latifundiaires, à l’armée et à la police (de statut militaire) qu’à des cartels très présents.
</p><p>
	Cette situation se vérifie aussi en Amérique centrale et dans les Andes. Au <a href="http://fr.rsf.org/perou.html" target="_blank">Pérou</a> et en <a href="http://fr.rsf.org/colombie.html" target="_blank">Colombie</a>, la couverture du narcotrafic, de la corruption mais aussi des conflits fonciers ou miniers expose fortement les journalistes aux représailles. Ténu mais réel, l’espoir d’un prochain accord de paix entre le gouvernement de Bogotá et la guérilla des Forces armées révolutionnaires de Colombie (FARC) ne saurait éliminer la donne du narco-paramilitarisme, elle aussi héritée des années de combat. Combien de journalistes, et avec eux des syndicalistes, avocats et représentants d’associations, subissent la pression, souvent fatale, d’unités paramilitaires reconstituées telles que les <a href="http://fr.rsf.org/predator-otoniel-et-los-urabenos-paramilitaires,44476.html" target="_blank">Urabeños ou les Rastrojos</a> ?</div>
	Au <a href="http://fr.rsf.org/mexique.html" target="_blank">Mexique</a>, ces prédateurs ont pour nom <a href="http://fr.rsf.org/spip.php?page=predateur&amp;id_article=44477" target="_blank">Zetas</a>, parmi d’autres organisations criminelles sévissant avec la complicité d’autorités locales – parfois fédérales – corrompues. Le pays traîne l’effroyable bilan de quatre-vingt-huit journalistes tués et dix-huit disparus entre 2000 et 2013, une séquence aggravée par ladite « offensive fédérale contre les cartels » menée sous la présidence de Felipe Calderón (2006-2012) qui aura fait plus de soixante mille morts au sein de la population.
</p><p>
	Le crime organisé et son infiltration entravent de même l’investigation et l’information plus au sud, comme au <a href="http://fr.rsf.org/bresil.html" target="_blank">Brésil</a> et au <a href="http://fr.rsf.org/paraguay.html" target="_blank">Paraguay</a>. Dans ces pays comme dans d’autres, la fragile condition du journaliste doit bien souvent à son manque de statut, à une faible solidarité interne à la profession mais aussi à la tragique inféodation de médias, surtout régionaux, aux centres de pouvoir. Véritable entorse au pluralisme et à l’indépendance de la presse, <a href="http://fr.rsf.org/bresil-le-pays-aux-trente-berlusconi-les-24-01-2013,43937.html" target="_blank">le « colonélisme » brésilien</a> fait du journalisme l’instrument des barons locaux, à la merci de règlements de comptes politiques parfois mortels.
</p><p>
	Jouet politique, le journaliste, et avec lui son média, l’est aussi dans des pays confrontés à une forte polarisation, où l’opposition entre secteur privé et secteur public – ou plutôt d’État – vire à l’affrontement. Le <a href="http://fr.rsf.org/venezuela.html" target="_blank">Venezuela</a> en est une illustration extrême. Les nombreuses périodes de campagne électorale y démultiplient les occasions d’invectives et d’agressions. Ce climat déteint aussi en <a href="http://fr.rsf.org/equateur.html" target="_blank">Équateur</a> et en <a href="http://fr.rsf.org/bolivie.html" target="_blank">Bolivie</a>, et dans une moindre mesure en <a href="http://fr.rsf.org/argentine.html" target="_blank">Argentine</a>.
</p>
	<h5>ÉTATS-UNIS, BRÉSIL : LES GÉANTS DU NOUVEAU MONDE NE MONTRENT PAS L’EXEMPLE</h5>
<p>
	Superpuissance pour l’un, puissance émergente pour l’autre. L’un a longtemps incarné la démocratie consolidée où les libertés publiques sont reines. Fort d’une Constitution démocratique adoptée trois ans seulement après la fin de sa dictature (1964-1985), l’autre a créé au cours des années Lula (2003-2010) les conditions de développement d’une société civile puissante. Riches de leurs diversités, <a href="http://fr.rsf.org/etats-unis.html" target="_blank">États-Unis</a> et Brésil devraient porter au plus haut la liberté de l’information à la fois comme norme juridique et comme valeur. La réalité est hélas loin de correspondre à cette ambition.
</p><p>
	Aux États-Unis, le 11 septembre 2001 génère un dilemme de fond entre les impératifs de sécurité nationale et les principes du premier amendement de la Constitution. Celui-là même qui consacre le droit de tout individu à informer et à être informé. Le socle constitutionnel de 1787 a fortement tremblé sur ses bases au cours du double mandat de George W. Bush, du fait de pressions voire d’emprisonnement de certains journalistes refusant de livrer l’identité de leurs sources ou leurs archives à la justice fédérale.</div>
	<div>
</p><p>
	Depuis la prise de fonctions de Barack Obama, la situation ne s’est guère améliorée sur le fond. On ne traque plus le journaliste ? On chasse sa source en l’utilisant parfois comme rabatteur. Ce ne sont pas moins de huit individus qui ont été inculpés au titre de l’<a href="http://fr.rsf.org/etats-unis-l-abus-d-espionage-act-est-22-05-2013,44649.html" target="_blank"><i>E</i><i>sp</i><i>ionage Act </i></a>depuis l’accession au pouvoir de Barack Obama, contre trois sous l’administration Bush. L’année 2012 fut en partie celle de <strong><a href="http://fr.rsf.org/rsf-et-wikileaks-interpellent-les-03-07-2013,44887.html" target="_blank">Julian Assange</a></strong>, le fondateur de WikiLeaks. L’année 2013 retiendra le nom d’<strong><a href="http://fr.rsf.org/etats-unis-etats-unis-prism-verizon-surveillance-generalisee-10-06-2013,44747.html" target="_blank">Edward Snowden</a></strong>, informaticien de la National Security Agency qui dénonça les programmes de surveillance massive développés par les services de renseignements des États-Unis. Le « donneur d’alerte », voilà l’ennemi. D’où la peine de trente cinq ans de prison infligée au soldat <a href="http://fr.rsf.org/etats-unis-une-peine-de-35-ans-de-prison-21-08-2013,45086.html" target="_blank">Manning</a>, soupçonné d’être la « taupe » de <em>WikiLeaks</em>.
</p><p>
	Une peine bien congrue comparée à celle encourue par le journaliste indépendant <strong><a href="http://fr.rsf.org/etats-unis-accuse-d-etre-un-hacker-le-11-07-2013,44922.html" target="_blank">Barrett Brown</a></strong> pour une inculpation de hacking : cent cinq ans de réclusion. Dans un climat généralisé de traçage des sources et des données, l’année 2013 restera enfin celle du scandale <em>Associated Press</em>, surgi avec l’aveu de saisie des relevés de lignes téléphoniques de l’agence de presse par le Département de la Justice.
</p><p>
	Au nord, le journalisme d’investigation vacille. Au sud, le journalisme au quotidien est toujours synonyme de risques et de périls. Avec cinq journalistes tués au cours de l’année 2013, le Brésil se hisse au sinistre rang de pays le plus meurtrier du continent pour la profession, une place tenue jusqu’alors par un Mexique bien plus sanglant.
</p><p>
	Ces tragédies, le Brésil les doit bien sûr à son insécurité toujours élevée. La prégnance du crime organisé dans certaines régions rend risqué le traitement de thèmes tels que la corruption, la drogue ou le trafic de matières premières. Les mafias veillent. Les autorités aussi. Réprimant parfois par le feu, elles sévissent beaucoup par la procédure. Journaliste et blogueur en croisade contre le trafic de bois précieux, <strong><a href="http://fr.rsf.org/bresil-avalanche-de-poursuites-25-02-2011,39627.html" target="_blank">Lúcio Flávio Pinto</a></strong> cumule pas moins de trente-trois poursuites judiciaires à son encontre. Paradoxe de la révocation en 2009 de la loi de presse de 1967 héritée du régime militaire : les injonctions de censure contre des médias et des journalistes embouteillent à présent les tribunaux, à la demande d’hommes politiques servis par une justice complaisante.</div>
</p><p>
Ces hommes politiques sont bien souvent ceux qu’on appelle « colonels », gouverneurs ou parlementaires, propriétaire de leur État. Localement, ils colonisent les titres et les fréquences, quand à l’échelle nationale dix grands groupes familiaux se partagent l’espace de diffusion. Le « printemps brésilien » durement réprimé a également porté la contestation contre un modèle médiatique devenu obstacle au pluralisme. Au grand dam de nombreux médias communautaires et alternatifs, le géant tarde ici à se réformer.
</p>
	<div class="encadre">
	<h6>Brésil : un « printemps » plombé</h6>
<p>	La très forte répression policière qui a sévi au Brésil en 2013 s’est aussi abattue sur les acteurs de l’information. C’est au mois de juin qu’éclatent des protestations d’envergure à l’annonce d’une augmentation des tarifs de transports à São Paulo. L’embrasement gagne tout le pays, la population admettant mal les dépenses pharaoniques engagées dans la perspective de la Coupe du monde de 2014 et des jeux Olympiques de 2016. Ce « printemps brésilien » donne également lieu à une forte remise en question du modèle médiatique dominant. Il souligne enfin les sinistres habitudes conservées par les polices militaires des États depuis l’époque de la dictature. Une centaine de journalistes auront <a href="http://fr.rsf.org/bresil-avalanche-de-poursuites-25-02-2011,39627.html" target="_blank">subi des violences</a> durant les manifestations, dont plus des deux tiers sont attribués aux forces de l’ordre.
</p></div>
	<h5>LA RÉGULATION DU PAYSAGE MÉDIATIQUE, NOUVELLE BASTILLE DES GAUCHES CONTINENTALES</h5>
	<div>
<p>
	Les fréquences se redistribuent-elles plus facilement que les lopins de terre ? On sait combien la réforme agraire constitue de longue date un marqueur identitaire pour une Amérique latine longtemps championne des inégalités sociales. Il trouve une forme d’écho dans le récent défi posé aux gouvernements progressistes du sud de la région : la démocratisation des supports d’information et de diffusion.
</p><p>
	À l’image de l’espace cultivable, le champ médiatique latinoaméricain se distingue par sa très forte concentration aux mains d’oligopoles vitrines des oligarchies locales et nationales. Ce <i>s</i><i>tatu</i><i> </i><i>q</i><i>u</i><i>o </i>a prévalu à la faveur de mécanismes de radiodiffusion entérinés sous les dictatures militaires des années 1960 et 1970, quand les médias constituaient une chasse gardée sous contrôle. La fin de la censure systématique n’a malheureusement pas éliminé une surconcentration qui fait toujours obstacle à un réel pluralisme. Le Brésil, le <a href="http://fr.rsf.org/chili.html" target="_blank">Chili</a> et la Colombie illustrent cette situation. Plus grave, les liens incestueux entre médias dominants et centres de pouvoir dictent encore l’agenda politique de certains pays. Ces mêmes médias dominants ont, en effet, joué un rôle clé lors des coups d’État survenus en 2009 au Honduras et en 2012 au Paraguay.
</p><p>
	Ailleurs, le modèle médiatique connaît une profonde remise en question sous l’impulsion de gouvernements progressistes portés par la vague électorale des années 2000. Mais s’agit-il de réguler l’espace de diffusion ou d’encadrer les médias et leurs acteurs ? Les réponses apportées selon les pays présentent d’importants contrastes, dans un climat polarisé.
</p><p>
	En Argentine, comme en <a href="http://fr.rsf.org/uruguay.html" target="_blank">Uruguay</a>, c’est une stricte réforme du cadre audiovisuel qui est à l’œuvre à la faveur de législations appelées Loi sur les services de communication audiovisuelle (LSCA) de part et d’autre du Río de la Plata. Adoptée en 2009, la LSCA argentine aura été pionnière en son genre en réservant un tiers de l’espace de fréquences aux organisations à but non lucratif. Cette disposition offre une vraie chance à des médias communautaires nombreux sur le continent mais privés de relais, voire criminalisés. En vertu de ses clauses anticoncentration, la LSCA est venue logiquement contrarier les intérêts du groupe <em>Clarín</em>, en conflit ouvert avec la présidente Cristina Kirchner depuis 2008. Après quatre ans de bataille judiciaire, le 29 octobre 2013, la Cour suprême a <a href="http://fr.rsf.org/argentine-la-loi-des-communications-30-10-2013,45396.html" target="_blank">déclaré constitutionnels</a> les deux articles contestés par l’oligopole, imposant pour l’un une cession des surplus de fréquences et pour l’autre une limitation de couverture d’une même entreprise sur un même territoire.
</p>
	<div class="encadre">
	<h6>Uruguay : un modèle de législation</h6>
<p>	Votée à la Chambre des députés le 10 décembre 2013, la <a href="http://fr.rsf.org/uruguay-ajustements-et-nouveau-defi-pour-12-12-2013,45601.html" target="_blank">Loi sur les services de communication audiovisuelle</a> (LSCA) pourrait devenir une référence en matière de régulation des médias. Le pays a été pionnier dans la région avec sa loi <i>a</i><i>d hoc </i>sur les radios communautaires adoptée en 2007. La LSCA prévoit une redistribution des fréquences en trois tiers pour les différents types de médias : privés, publics et communautaires. Or la LSCA offre une garantie majeure en interdisant toute attribution de fréquence discrétionnaire, en fonction de la ligne éditoriale des stations et chaînes concernées. La faible polarisation médiatique du pays comparé à ses voisins joue à son tour en faveur de la nouvelle loi, comme le large débat associant la société civile qui a présidé à l’élaboration de celle-ci.</div>
</p><p>	Les dispositions générales de la LSCA ont directement influencé d’autres législations régionales dédiées à un partage équitable des fréquences selon les types de médias (publics, privés et communautaires). La réforme de la loi de télécommunications en Bolivie (2011) entérine ce principe, tout comme la loi de communication adoptée en Équateur le 14 juin 2013. La critique perdure concernant cette dernière, qui entend également promouvoir l’information « vraie, opportune, contrastée, contextualisée et d’intérêt public ».
</p><p>
	Face à des médias privés souvent agressifs et eux-mêmes décriés, le gouvernement équatorien dispose à présent de l’arme légale. Il peut aussi compter sur un consortium de médias publics ou sous tutelle (<i>incautados</i>) désormais dominant parmi les fréquences nationales. Il tient enfin à sa main une importante manne publicitaire officielle indispensable à la survie de nombre de médias régionaux. Au Venezuela, la logique de « guerre médiatique » surgie avec le coup d’État de 2002 l’a emporté sur toute forme de régulation. L’espace audiovisuel national est presque entièrement soumis à l’exécutif et à ses annonces publiques obligatoires, baptisées <i>cadenas</i>.</div>
</p>

<?php include "fr-footer.php" ?>