<?php 
	$selected 	= "asie";
	$title 		= "Classement de la liberté de la presse 2014 | AFRIQUE"
?>
<?php include "fr-header.php" ?>

<article>
	<h2>Asie - Pacifique</h2>
	<h5>LA CHINE, UN GRAND FRÈRE QUI SURVEILLE ET EXPORTE SON MODÈLE DE CENSURE</h5>
	<p>
	Dans un discours prononcé le lendemain de sa nomination à la tête du Parti communiste chinois (PPC), en novembre 2012, Xi Jinping s’adresse directement aux journalistes : « Amis de la presse, la Chine doit en apprendre davantage sur le monde et le monde doit en apprendre davantage sur la Chine. J’espère que vous continuerez à faire plus d’efforts et à contribuer à la compréhension mutuelle entre la Chine et les autres nations du monde. »
	</p>
	<div>
<p>
	Malheur aux journalistes qui ont compris : « Décrivez la dure réalité de la Chine ! » là où il fallait entendre : « Suivez la propagande du Parti à la lettre ! » Depuis ce discours, les autorités ont multiplié les arrestations de journalistes et de blogueurs, durci leur politique de répression envers les cyberdissidents, renforcé le contrôle de l’information et la censure en ligne et intensifié les limitations imposées <a href="http://fr.rsf.org/chine-renouvellement-de-visa-refuse-pour-02-01-2013,43852.html">à la presse étrangère</a>.
</p><p>
	Embarrasser un officiel ou dénoncer un scandale de corruption, c’est prendre le risque de subir la dégradation publique. Le journaliste Luo Changping, contraint de quitter le magazine <i>Cai</i><i>j</i><i>in</i><i>g </i>en novembre 2013<i>,</i><i> </i><a href="http://fr.rsf.org/chine-le-journaliste-liu-hu-formellement-11-10-2013,45320.html">Liu Hu</a>, reporter du quotidien <i>Ne</i><i>w Express, </i>arrêté pour diffusion de « fausses informations », ou encore le <a href="http://fr.rsf.org/chine-censure-expulsion-et-espionnage-le-05-02-2013,44020.html"><i>Ne</i><i>w York Times </i></a>figurent parmi les derniers exemples de journalistes et de médias réprimés en raison de leur travail d’investigation. Les avocats des droits de l’homme et des cyberdissidents, comme <a href="http://fr.rsf.org/chine-le-cyberdissident-xu-zhiyong-28-01-2014,45788.html">Xu Zhiyong</a> et Guo Feixiong (Yang Maodong), emprisonnés sous des prétextes fallacieux et sans même avoir été jugés, ont payé le plus lourd tribut de ces douze derniers mois.
</p>
	</div>
	<p>
	L’envoi quotidien de « directives » à la presse traditionnelle par le département de la Propagande, <a href="http://fr.rsf.org/chine-lutte-contre-les-rumeurs-et-vagues-03-10-2013,45282.html">la censure en ligne permanente</a>, les arrestations arbitraires en hausse et l’emprisonnement du plus grand nombre de journalistes et net-citoyens au monde, y compris le Prix Nobel de la paix 2010 <a href="http://fr.rsf.org/chine-n-oublions-pas-liu-xiaobo-24-12-2013,45669.html">Liu Xiaobo</a>, font de la Chine un véritable modèle de censure et de répression. Ce modèle essaime hélas ailleurs dans la région.
</p><p>
	Ainsi au Vietnam, les autorités de Hanoï redoublent de zèle en matière de répression et de contrôle de l’information, au point même de talonner le grand frère chinois. Renforcement des ressources destinées à la surveillance d’Internet, <a href="http://fr.rsf.org/vietnam-l-ecrivain-et-blogueur-pham-viet-17-06-2013,44800.html">vagues d’arrestations</a>, <a href="http://fr.rsf.org/vietnam-le-proces-de-deux-blogueurs-16-08-2013,45059.html">procès iniques</a> et adoption continue de <a href="http://fr.rsf.org/vietnam-le-vietnam-veut-interdire-aux-02-08-2013,45007.html">directives liberticides</a> déclinent le calvaire des acteurs de l’information œuvrant en marge du système. Le pays demeure à ce jour la deuxième prison au monde pour les blogueurs et net-citoyens. Vingt-six des trente-quatre blogueurs actuellement incarcérés l’ont été depuis l’accession de Nguyen Phu Trong au poste de secrétaire général du Parti communiste du Vietnam. En septembre 2013, le Parti a encore franchi un cap répressif avec l’instauration du <a href="http://fr.rsf.org/vietnam-le-vietnam-veut-interdire-aux-02-08-2013,45007.html">décret 72</a>, qui rend illégal l’usage des blogs et des réseaux sociaux pour partager des informations sur l’actualité. Le Parti s’est ainsi engagé dans une lutte sans merci contre le Web 2.0, qu’il considère comme un contrepoids encombrant à une presse qu’il tient à sa main.
	</p>
	<h5>LES DÉMOCRATIES D’ASIE ET DU PACIFIQUE</h5>
	<div>
<p>
	L’année 2013 a témoigné de l’extrême susceptibilité de certains gouvernements de la région Asie-Pacifique face à la critique publique, même sous régime démocratique. En témoignent la multitude de procédures judiciaires, parfois assorties de peines disproportionnées, engagées contre des journalistes sous la pression des centres de pouvoir.
</p><p>
	Avec le crime de « lèse-majesté », le gouvernement thaïlandais dispose d’un outil efficace pour intimider ou faire taire les insolents. La peine avec sursis infligée à <a href="http://fr.rsf.org/thailande-rsf-la-justice-thailandaise-doit-07-11-2013,45438.html">Chiranuch Premchaiporn (Jiew)</a>, directrice du quotidien en ligne <i>Prachatai</i>, pour des « commentaires critiques à l’encontre de la monarchie » ou la <a href="http://fr.rsf.org/thailande-proces-de-somyot-prueaksakasemsuk-23-01-2013,43935.html">condamnation à onze années de prison</a> du rédacteur en chef du magazine bimensuel <i>Voice</i><i> </i><i>o</i><i>f Thaksin</i>, Somyot Prueksakasemsuk, constituent des exemples marquants. Ces verdicts ont, en effet, un impact dissuasif sur l’ensemble de la presse nationale.
</p><p>
	En Corée du Sud, les journalistes indépendants Kim Ou-joon et Choo Chin-woo, auteurs du podcast « Naneun Ggomsuda », ont essuyé les foudres de la présidence. Réprimés pour leur ton satirique, les journalistes ont été accusés d’avoir « diffusé de fausses informations » et des « informations diffamatoires » à l’encontre du frère et du père de la présidente, Park Geun-hye. Aux Tonga et en Papouasie-NouvelleGuinée, quatre journalistes ont été <a href="http://fr.rsf.org/papouasie-n-guinee-trois-journalistes-releves-de-08-11-2013,45440.html">sanctionnés ou condamnés</a> à des amendes pour avoir « critiqué » le Premier ministre.
</p><p>
	Les démocraties asiatiques ne sont pas davantage exemptes de « zones interdites », où l’information demeure soumise au black-out et à la censure. Dans la province indienne du Cachemire et dans la Papouasie occidentale indonésienne, des politiques de contrôle liberticides entravent gravement l’activité des journalistes. Au Cachemire, le gouvernement impose même un couvre-feu et <a href="http://fr.rsf.org/inde-censure-totale-des-medias-d-13-02-2013,44065.html">bloque régulièrement</a> les réseaux Internet et 3G.
</p>
	<h6>Surveillance et secret des sources</h6>
<p>
	En Australie, l’absence de législation pour protéger de manière adéquate les sources des journalistes continue à faire peser sur eux la menace d’emprisonnement pour « outrage à la Cour » en cas de refus de les divulguer. Pas moins de sept requêtes de ce type ont été soumises à la justice pour la seule année 2013. L’interception des métadonnées du reporter Jon Stephenson par les forces militaires néo-zélandaises, qui jugeaient ses articles trop critiques, et l’espionnage téléphonique dont a été victime la journaliste<em> Andrea Vance</em> illustrent la défiance croissante des autorités envers les médias et leur rôle de contre-pouvoir.
</p>
	<h6>La menace chinoise</h6>
<p>	Le poids économique croissant de la Chine permet aujourd’hui au gouvernement de Pékin d’étendre son influence sur les médias hongkongais, macanais et taïwanais, jusqu’ici relativement épargnés par la censure politique. L’indépendance des médias de ces trois territoires, historiquement revendiqués par la Chine, y est sévèrement remise en cause. L’assujettissement croissant de l’exécutif hongkongais au contrôle du Parti communiste chinois, et les pressions que ce dernier exerce sur les médias à travers son « bureau de liaison » compromettent de plus en plus un pluralisme jusqu’alors à peu près préservé. À Taïwan, le rachat du <i>Chi</i><i>n</i><i>a Times </i>par le groupe Want Want au bénéfice du PCC menace le pluralisme de la presse dans cette république insulaire.
</p>	
	<div class="encadre">
	<h6>Fukushima censuré</h6>
	<p>
		Arrestations, perquisitions de domicile, convocations par les services du Renseignement intérieur, menaces de <a href="http://fr.rsf.org/japon-fukushima-acharnement-judiciaire-10-07-2012,42990.html">poursuites judiciaires</a>, qui eût pu croire que les journalistes indépendants prenaient autant de risques en couvrant l’après-Fukushima ? Depuis l’accident nucléaire en 2011, le système unique au monde des « Kisha clubs », ces clubs de presse dont seuls les membres sont accrédités auprès des autorités, exacerbe les discriminations dont sont victimes <a href="http://fr.rsf.org/japon-les-journalistes-freelance-06-11-2012,43639.html">les journalistes free-lance</a> et la presse étrangère. Souvent exclus des conférences de presse organisées par TEPCO et le gouvernement, privés d’une information réservée aux grands médias au sein desquels l’autocensure est la règle, les journalistes indépendants luttent à armes inégales contre le « village nucléaire ». Après que le gouvernement de Shinzo Abe a légiféré sur les « <a href="http://fr.rsf.org/japon-rsf-demande-au-premier-ministre-27-11-2013,45514.html">secrets d’État</a> », leur combat pour la liberté d’informer s’annonce encore plus dangereux.
</p>
</div>
	<h5>VIOLENCE ET IMPUNITÉ INQUIÉTANTES SUR LE SOUS-CONTINENT INDIEN</h5>
	<div>
<p>
	Pour la seconde année consécutive, le sous-continent indien est la région d’Asie qui enregistre la plus forte hausse d’insécurité pour les acteurs de l’information. L’évolution la plus inquiétante réside dans le caractère ciblé des attaques. Au Népal, les militants maoïstes redoublent d’<a href="http://fr.rsf.org/nepal-22-journalistes-menaces-de-morts-25-01-2013,43955.html">hostilité envers des journalistes</a> critiques à l’encontre de leurs leaders politiques. L’approche des élections à l’Assemblée constituante de novembre 2013 a malheureusement été propice à ce climat.
</p><p>
	L’Inde établit un triste record, avec pas moins de <a href="http://fr.rsf.org/inde-un-journaliste-experimente-tabasse-11-12-2013,45599.html">huit journalistes</a> et un collaborateur des médias tués, dont la moitié au cours de représailles préméditées. Ce <a href="http://fr.rsf.org/71-journalistes-ont-ete-tues-en-18-12-2013,45633.html">bilan</a>, deux fois plus lourd que celui de 2012, dépasse même celui du Pakistan, longtemps le pays le plus meurtrier au monde pour les journalistes. Multiples sont les menaces – mafia, forces de sécurité, manifestants, groupes armés – pesant sur les professionnels des médias. L’inefficacité des autorités locales à mener des enquêtes, parfois tout juste expédiées, et l’inertie des autorités fédérales pour lutter contre l’impunité favorisent l’insécurité et l’autocensure.
</p><p>
	L’année 2013 est également très sombre pour la liberté de l’information au Bangladesh. Dès le mois de février, les <a href="http://fr.rsf.org/bangladesh-le-blogueur-asif-mohiuddin-arrete-03-04-2013,44294.html">blogueurs indépendants</a> couvrant notamment les procès d’anciens leaders politiques accusés de crimes de guerre durant la guerre de libération de 1971 sont devenus les cibles d’agressions incessantes. L’un d’eux, <a href="http://fr.rsf.org/bangladesh-un-blogueur-egorge-dans-la-18-02-2013,44092.html">Ahmed Rajib Haider</a>, y a laissé la vie. <a href="http://fr.rsf.org/bangladesh-un-blogueur-grievement-blesse-a-l-16-01-2013,43915.html">Asif Mohiuddin</a>, lui, a été poignardé à plusieurs reprises par des militants islamistes qui l’accusaient d’avoir blasphémé et insulté le Prophète. Entre les mois de mai et d’octobre, les journalistes ont subi le feu croisé de la police et des émeutiers durant des manifestations réclamant l’instauration d’une loi contre le blasphème. Pendant ce temps, l’impunité demeure totale pour les assassins des journalistes <a href="http://fr.rsf.org/bangladesh-rsf-demande-la-creation-d-une-11-02-2013,44058.html">Sagar Sarowar et Meherun Runi</a>, tués en février 2012.
</p><p>
	Cette même mauvaise volonté pour rendre la justice se retrouve pareillement au Pakistan, dont le gouvernement semble impuissant face aux groupes armés, talibans, djihadistes mais aussi l’appareil militaire, qualifié d’« État dans l’État » par de nombreux observateurs internationaux. Au cours de l’année 2013, sept journalistes ont été assassinés dans l’exercice de leurs fonctions. <a href="http://fr.rsf.org/pakistan-double-attentat-a-quetta-trois-12-01-2013,43903.html">Quatre d’entre eux</a>, Mohammad Iqbal (<i>News Network International</i>), Saifur Rehman et Imran Shaikh (<i>Sama</i><i>a News</i>) et <a href="http://fr.rsf.org/pakistan-un-second-journaliste-abattu-en-01-03-2013,44158.html">Mehmood Ahmed Afridi</a>, ont été tués au Baloutchistan, province la plus meurtrière du pays. Si les groupes armés constituent la principale menace pour les journalistes pakistanais, les agences de renseignement, en premier lieu desquelles l’Inter-Services Intelligence (ISI), continuent de sévir. Les journalistes qui osent témoigner ont confirmé que les militaires continuent d’avoir recours à la surveillance, aux <a href="http://fr.rsf.org/pakistan-un-journaliste-detenu-au-secret-18-10-2013,45344.html">enlèvements</a>, à la torture et aux assassinats.
</p>
	</div>
	<div class="encadre">
	<h6><i>Uthaya</i><i>n </i>: pour certains médias, la guerre <b>es</b><b>t loin d’être terminée</b></h6>
	<p>En avril 2013, <i>Uthaya</i><i>n</i>, le quotidien en langue tamoule, fait l’objet de <a href="http://fr.rsf.org/sri-lanka-deuxieme-attaque-contre-uthayan-en-15-04-2013,44376.html">deux violentes attaques</a> à dix jours d’intervalle. Deux de ses employés frôlent la mort. Son imprimerie est incendiée, ses locaux ravagés. Ces raids ne sont pourtant pas à mettre sur le compte de la guerre civile opposant le LTTE et l’armée régulière, celle-ci s’étant officiellement achevée en mai 2009. Fondé en 1985, <i>Uthaya</i><i>n</i>, seul journal à ne pas interrompre ses activités durant le conflit, est aujourd’hui lu par près de cent mille Tamouls sur les cinq cent mille qui peuplent la péninsule. N’hésitant pas à critiquer le pouvoir autoritaire du clan Rajapaksa, le quotidien continue à payer au prix fort son refus de se soumettre à la fois au gouvernement et aux militaires. Six de ses collaborateurs ont trouvé la mort dans l’exercice de leur métier. <i>Uthaya</i><i>n </i>reçoit en décembre 2013 l<a href="http://fr.rsf.org/sri-lanka-le-prix-rsf-pour-la-liberte-de-la-27-11-2013,45517.html">e prix Reporters sans frontières</a> de la liberté de la presse.
</p>
	</div>
	<h5>BIRMANIE : LE « PRINTEMPS » DÉMOCRATIQUE PERD DU SOUFFLE</h5>
	<div>
<p>
	L’ouverture et la démocratisation de la Birmanie seraient-elles en passe de s’essouffler ? Un nombre croissant d’organisations internationales de défense des droits de l’homme s’en inquiètent à juste titre. L’euphorie générale née des amnisties successives de prisonniers politiques, en octobre 2011 et janvier 2012, n’est plus de saison. Le gouvernement de Rangoun peine à résoudre les conflits civils et ethniques qui minent le pays. Disposant désormais d’une plus grande liberté d’expression, <a href="http://fr.rsf.org/birmanie-le-gouvernement-birman-entre-07-03-2013,44175.html">la société civile gronde contre les autorités</a>.
</p>
	</div>
	<div>
<p>
	La mise sur le marché de quotidiens privés constitue l’une des grandes nouveautés de l’année 2013. En mars, le gouvernement a annoncé avoir autorisé le lancement de huit quotidiens d’information et étudier les requêtes d’au moins six autres publications, dont certaines dirigées par les « médias de l’exil » qui ont désormais pignon sur rue à Rangoun. Une vingtaine de ces nouveaux journaux circulent déjà dans les principales villes du pays. La mutation du paysage médiatique birman doit aussi au lancement de plusieurs médias en ligne voire de stations de radio. Le processus s’accélère grâce aux nombreuses aides apportées par les organisations internationales de promotion et de défense des médias, et aux soutiens de ces dernières en matière de formation technique et éthique. L’effort bénéficie également aux minorités, dont certaines bénéficient d’une presse locale dans leur langue.
</p><p>
	Le cadre légal évolue plus timidement. Le gouvernement et le Parlement ont certes entériné leurs engagements, pris en 2012, de mettre un terme à la censure préalable et d’octroyer davantage de liberté aux médias et aux organisations de presse. Pour autant, la promesse d’élaborer une législation conforme aux standards internationaux n’a toujours pas été tenue. Le 4 mars 2013, le gouvernement soumet sans la moindre consultation à la Chambre basse de l’Assemblée nationale (Pyidaungsu Hluttaw) un <a href="http://fr.rsf.org/birmanie-la-chambre-haute-du-parlement-ne-09-07-2013,44915.html">projet de loi sur la presse</a> nettement liberticide. La loi sur les entreprises d’imprimerie et de publication et la dernière version du projet de loi sur les médias audiovisuels témoignent à leur tour de l’ambivalence des autorités quant au respect réel des droits fondamentaux.
</p><p>
	La Birmanie est donc loin d’avoir achevé sa transition démocratique. Le processus de réformes est pourtant suivi avec un fort intérêt au-delà des frontières birmanes, en premier lieu par les pays voisins. Au Laos, où la situation de la liberté de l’information connaît une stagnation préoccupante ; au Cambodge ; à <a href="http://fr.rsf.org/singapour-les-sites-internet-d-information-30-05-2013,44688.html">Singapour</a>, où les autorités se crispent ; ou encore au Vietnam toujours soumis à l’autoritarisme du parti unique. Les gouvernements et les populations de ces pays surveillent le développement d’un nouveau modèle régional de gouvernance du côté de Rangoun. Un modèle encore bien loin d’avoir fait toutes ses preuves. La Birmanie servira-t-elle de mètre étalon à une évolution positive de la liberté de l’information en Asie du Sud-Est ? La question reste en suspens.
</p>
	</div>
	</div>
<article>

<?php include "fr-footer.php" ?>