<?php 
	$selected 	= "europe-est";
	$title 		= "Classement de la liberté de la presse 2014 | AFRIQUE"
?>
<?php include "fr-header.php" ?>

	<h2>Europe de l’Est et Asie centrale</h2>
<h5>LA TENTATION AUTORITAIRE DES MODÈLES RÉGIONAUX</h5>
<h6>Sotchi 2014 : derrière la vitrine olympique, la guerre du Kremlin contre la société civile</h6>
<div>
<p>
Plus de deux décennies après l’implosion de l’Union soviétique, Moscou demeure une référence essentielle pour toute la région, à laquelle l’unissent de forts liens culturels, économiques et politiques. L’ouverture dans le faste des XXIIe jeux Olympiques d’hiver à Sotchi, en février 2014, ne doit pas occulter la réalité du bras de fer qui oppose en Russie une société civile toujours plus affirmée à un État toujours plus répressif.
</p><p>
Les vastes manifestations de 2011-2012 ont banalisé la critique du régime. L’autocensure des médias est pourtant loin d’avoir disparu. Les télévisions fédérales restent sous contrôle et face au « retour de la politique en Russie », les autorités ont fait le choix de la répression. Depuis que Vladimir Poutine a repris possession du Kremlin en mai 2012, les <a href="http://fr.rsf.org/russie-jusqu-ou-ira-la-douma-dans-sa-19-12-2013,45649.html">lois liberticides s’empilent</a>. Activistes, médias et blogueurs n’échappent pas au couperet : réintégration de la diffamation dans le domaine pénal, mise en place d’une liste noire de sites Internet, élargissement démesuré de la notion de « haute trahison », etc. Les « valeurs traditionnelles » sont invoquées pour justifier de nouvelles restrictions à la liberté de l’information. Parmi elles, la <a href="http://fr.rsf.org/russie-le-neoconservatisme-de-la-douma-14-06-2013,44787.html">pénalisation de la « propagande homosexuelle » et de l’« insulte aux sentiments des croyants »</a>.
</p><p>
Des professionnels des médias sont privés de liberté du fait de leurs activités. À Sotchi, le <a href="http://fr.rsf.org/russie-enquete-suspecte-contre-un-21-06-2013,44832.html">journaliste free-lance Nikolaï Iarst</a> a été assigné à résidence pendant six mois et demeure inculpé dans le cadre d’une affaire de détention de drogue montée de toutes pièces. À Rostov-sur-le-Don, le <a href="http://fr.rsf.org/russie-les-juges-de-rostov-sur-le-don-02-01-2014,45690.html">blogueur Sergueï Reznik et le journaliste Alexandre Tolmatchev</a> sont emprisonnés sur la base d’accusations douteuses. Le photographe russe <a href="http://fr.rsf.org/russie-arctic-sunrise-denis-siniakov-19-11-2013,45479.html">Denis Siniakov et le vidéaste britannique Kieron Bryan</a>, qui couvraient les activités de militants de Greenpeace dans l’Arctique, ont passé deux mois en détention provisoire, accusés de « piraterie » et d’« hooliganisme ». L’impunité persistante entretient un climat d’insécurité, notamment dans le Caucase. Au moins trente-trois journalistes ont été assassinés du fait de leurs activités professionnelles en Russie depuis 2000.
</p>
</div>
<div>
<h6>La Turquie à la croisée des chemins</h6></p><p>
<p>Forte d’un rayonnement diplomatique et économique croissant, la Turquie se positionne comme un modèle de démocratie régionale, notamment pour les régimes issus des « printemps arabes ». Après dix ans de règne du parti islamo-conservateur AKP, l’emprise de l’armée sur la vie politique et les médias a disparu et un certain nombre de tabous liés à l’idéologie kémaliste se fissurent. De nouvelles lignes rouges tendent malgré tout à les remplacer. En dépit de timides réformes, la pratique judiciaire reste largement répressive. Le nombre de professionnels des médias emprisonnés se maintient à des niveaux inédits depuis le régime militaire : fin 2013, ils étaient une soixantaine, faisant de la Turquie l’une des plus grandes prisons du monde pour les journalistes. Malgré des directives visant à limiter le recours à la détention provisoire, les prisonniers restent souvent incarcérés des mois, voire des années, avant d’être jugés.
</p><p>
Après les combats les plus violents de la décennie, l’ouverture de négociations de paix entre le gouvernement de Recep Tayyip Erdoğan et les rebelles kurdes du PKK (Parti des travailleurs du Kurdistan) suscite de grands espoirs. Les autorités ont promis des réformes démocratiques. Elles sont urgentes. La plupart des journalistes emprisonnés et poursuivis font les frais d’une législation antiterroriste héritée des années de plomb. Une vingtaine d’articles du Code pénal complètent cet arsenal législatif liberticide. Au-delà des textes de loi, un règlement pacifique de la question kurde permettrait enfin de faire évoluer une culture judiciaire empreinte de réflexes paranoïaques et répressifs.
</p>
</div>
<p>Le mouvement de protestation sans précédent de l’été 2013 a démontré la soif de liberté de la société turque. Il a aussi mis au jour le manque de culture démocratique des forces de l’ordre, et la menace que pose pour le pluralisme la concentration croissante des grands médias entre les mains d’hommes d’affaires liés à l’État.
</p>
<div class="encadre">
<h6>Gezi, terrain miné pour les journalistes</h6></p><p>
<p>Cent cinquante-trois blessés, trente-neuf interpellés : entre mai et septembre 2013, les journalistes font largement les frais de la <a href="http://fr.rsf.org/turquie-au-moins-douze-journalistes-11-09-2013,45165.html">violente répression du mouvement de protestation antigouvernementale</a> en Turquie. Parfois pris à partie par les manifestants, ils sont aussi systématiquement pris pour cibles par les forces de l’ordre. Ce déchaînement de violence intervient dans un climat d’hystérie distillé par les discours officiels et un certain nombre de médias progouvernementaux : chroniqueurs critiques, utilisateurs des réseaux sociaux et correspondants des médias étrangers sont dépeints au mieux comme les agents d’un complot international destiné à renverser le régime, au pire comme des terroristes. L’autocensure se révèle dans toute son ampleur lorsque des chaînes d’information en continu omettent de retransmettre les violents affrontements qui secouent Istanbul. Les <a href="https://www.wefightcensorship.org/fr/censored/apres-gezi-nouvelle-vague-licenciements-journalistes-critiqueshtml.html">journalistes récalcitrants sont poussés vers la sortie</a> : pas moins de quatorze d’entre eux sont congédiés tandis que vingt-deux préfèrent démissionner. Quant aux chaînes qui couvrent au plus près les événements, elles écopent d’amendes astronomiques.
</p>
</div>
<h5>L’IMPUNITÉ DES DESPOTES PÉTROLIERS ET GAZIERS</h5>
<div>
<p>
Dans l’espace post-soviétique, les régimes les plus attentatoires à la liberté de l’information subissent peu de pressions de la part de la « communauté internationale ». Et pour cause : le Turkménistan, l’Ouzbékistan, le Kazakhstan et l’Azerbaïdjan sont également les pays les plus favorisés par la nature et le tracé des pipelines. Suffisamment riches pour se sentir intouchables, ces États sont en outre courtisés du fait de leur importance stratégique. C’est pour l’heure en toute impunité qu’ils mettent en coupe réglée les médias et jettent en prison les journalistes récalcitrants.
</p>
<h6>Glaciations despotiques et fuites en avant répressives</h6></p><p>
<p>Après vingt ans d’arbitraire absolu, le Turkménistan s’est formellement doté en janvier 2013 d’une <a href="http://fr.rsf.org/turkmenistan-premiere-loi-sur-les-medias-de-l-09-01-2013,43875.html">loi sur les médias</a>, proclamant officiellement le pluralisme et l’interdiction de la censure. Une fiction absolue dans un pays soumis au régime totalitaire du président Gourbangouly Berdymoukhammedov. L’ensemble des médias basés sur place reste contrôlé par l’État. Le journalisme indépendant n’est possible que dans la clandestinité, en collaboration avec des titres en exil. Avec tous les risques que cela comporte : <a href="http://fr.rsf.org/turkmenistan-deux-journalistes-retrouvent-enfin-18-02-2013,44089.html">Annakourban Amanklytchev et Sapardourdy Khadjiev</a> viennent de purger sept ans de prison dans des conditions effroyables. Les arrestations arbitraires sont monnaie courante. Le pays reste au voisinage de la Corée du Nord et de l’Érythrée dans les tréfonds du classement mondial de la liberté de la presse.
</p><p>
La censure la plus stricte prévaut également en Ouzbékistan, où pas moins de dix journalistes et net-citoyens sont derrière les barreaux. L’un d’entre eux a reçu le <a href="http://fr.rsf.org/maghreb-et-moyen-orient-un-journaliste-ouzbek-et-un-27-11-2013,45517.html">prix 2013 de la liberté de la presse</a> de Reporters sans frontières : Muhammad Bekjanov, ancien rédacteur en chef du journal <i>Er</i><i>k </i>et l’un des fers de lance du combat pour la démocratie, est emprisonné depuis près de quinze ans. Soumis à la torture, privé de soins, il est en danger de mort. Tout comme le journaliste indépendant <a href="http://fr.rsf.org/ouzbekistan-un-journaliste-en-grand-danger-26-06-2013,44857.html">Solidjon Abdourakhmanov</a>, incarcéré depuis 2008, coupable d’avoir enquêté sur les conséquences de la catastrophe écologique de la mer d’Aral. Non contentes de leur contrôle absolu sur les médias traditionnels, les autorités mettent ces dernières années un soin tout particulier à raffiner leurs techniques de censure du Net.
</p><p>
Pour des despotes au pouvoir depuis plus de vingt ans, la succession est une question épineuse. Comme son homologue ouzbek Islam Karimov, le président kazakh Noursoultan Nazarbaev n’a pas clairement désigné de successeur. Alors que les appétits s’aiguisent et que des accrocs apparaissent dans la stabilité dont jouissait le Kazakhstan depuis l’indépendance, la paranoïa et la volonté de contrôle du pouvoir vont croissant. Et la liberté de l’information est en chute libre. Au tournant 2012-2013, les <a href="http://fr.rsf.org/kazakhstan-en-un-mois-les-principaux-medias-d-28-12-2012,43750.html">principaux médias d’opposition nationaux ont tous été fermés</a>. À la capitale comme en province, procédures judiciaires et harcèlement administratif poursuivent les voix récalcitrantes.
</p><p>
La fuite en avant répressive vaut tout autant pour l’Azerbaïdjan. Alors que se multiplient les arrestations de journalistes et de blogueurs, c’est là aussi l’existence même du pluralisme médiatique qui est en danger. Les chaînes de télévision sont sous contrôle, les principales radios étrangères ont été bannies et le principal journal d'opposition, qui ne circule guère que dans la capitale, est <a href="http://fr.rsf.org/azerbaidjan-rsf-condamne-l-etouffement-27-02-2013,44145.html">proche de l'asphyxie économique</a>. Agressions, arrestations, campagnes de discrédit, enlèvements, menaces de mort attendent les journalistes et blogueurs récalcitrants. L'apparition de nouveaux médias alternatifs en exil parviendra-t-elle à sauver le pluralisme ?
</p>
</div>
<h6>Des despotes sans hydrocarbures</h6>
<p>Certains États post-soviétiques n’attendent cependant pas la manne pétrolière ou gazière pour réprimer les médias. Au Bélarus, les journalistes indépendants continuent de lutter à armes inégales contre la propagande de la « dernière dictature d’Europe ». Ceux qui couvrent les mouvements sociaux sont systématiquement interpellés. La justice et le KGB prétextent régulièrement la « lutte contre l’extrémisme » pour faire taire ceux qui refusent de se conformer à la ligne officielle. En 2013, l’album de photojournalisme <a href="https://www.wefightcensorship.org/fr/censored/voir-realite-en-face-extremiste-selon-kgbhtml.html"><i>Belarus Press Photo 2011 </i>a été interdit</a> et l’une des principales maisons d’édition indépendantes privée de licence. La <a href="http://fr.rsf.org/belarus-la-levee-de-l-embargo-financier-27-03-2013,44264.html">revue <i>Arche </i></a>et les médias indépendants basés à l’étranger, comme Belsat TV, sont confrontés à toutes sortes de tracasseries administratives.</p>
<h5>L’INFORMATION À L’ÉPREUVE DE SOCIÉTÉS POLARISÉES</h5>
<div>
<h6>Le quatuor de tête</h6></p><p>
<p>Dans l’édition 2014 du Classement mondial de la liberté de la presse, le quatuor de tête de la zone est le même que l’année passée. Malgré leur grande dispersion, la Moldavie, la Géorgie, l’Arménie et le Kirghizstan bénéficient tous d’un pluralisme important et d’une censure étatique relativement faible, mais la forte polarisation des sociétés se reflète dans le paysage médiatique et le climat de travail des journalistes, souvent pris à partie par divers groupes de pression. Dans des contextes où l’orientation politique des médias est largement corrélée avec l’identité de leurs propriétaires, l’indépendance des rédactions reste un défi majeur.
</p><p>
En Géorgie et en Arménie, les scrutins électoraux de 2013 se sont déroulés dans une atmosphère plus apaisée que les précédents. Les violences contre les journalistes ont été plus rares. L’audiovisuel public arménien a fait des progrès en termes d’impartialité, mais le contexte électoral a accentué la guerre de l’information dans les médias privés – guerre dans laquelle le pouvoir dispose d’avantages certains. L’alternance politique en Géorgie s’est traduite dans les médias : la <a href="http://fr.rsf.org/georgie-de-nombreuses-inconnues-pour-les-01-10-2012,43469.html">chaîne Imedi</a>, acquise en 2007 par des proches de l’ancien président Saakachvili, a été restituée à la famille de son actionnaire originel peu après les élections d’octobre 2012. La justice a ouvert une enquête pour transfert frauduleux d’actifs et blanchiment d’argent, impliquant le maire de Tbilissi. Élu Premier ministre, Bidzina Ivanichvili a annoncé la fermeture de la chaîne privée TV9, lancée en 2012 par son épouse et qui avait joué un grand rôle pour le propulser au pouvoir. La <a href="http://fr.rsf.org/georgie-il-est-urgent-de-garantir-l-08-03-2013,44187.html">nouvelle loi sur l’audiovisuel</a> devrait permettre de limiter les affrontements politiques au sein de la Radio-Télévision publique géorgienne, qui s’étaient traduits courant 2013 par une cascade de licenciements.
</p>
<h6>Ukraine et Tadjikistan entre deux eaux</h6></p><p>
<p>
L’indépendance des rédactions soulève les mêmes questions en Ukraine, où le <a href="http://fr.rsf.org/ukraine-changement-revoltant-de-direction-26-04-2013,44428.html">passage des médias d’un propriétaire à l’autre</a> s’est traduit par de brusques changements de ligne éditoriale, l’instauration de nouveaux tabous et de nombreux licenciements. L’adoption en seconde lecture d’une loi censée favoriser la transparence sur la propriété des médias se fait attendre. La crise politique ouverte en décembre 2013 et le <a href="http://fr.rsf.org/ukraine-la-liberte-de-l-information-enterree-16-01-2014,45739.html">brusque virage liberticide</a> pris par Kiev échappent à la période couverte par cette édition du classement mondial. Nul doute qu'ils pèseront de tout leur poids sur le classement de l'Ukraine dans l'édition 2015.
</p>
</div><p>
Les prémisses de cette dérive étaient néanmoins visibles : concentration croissante des principaux médias entre les mains d'oligarques proches du gouvernement, <a href="http://fr.rsf.org/ukraine-jusqu-ou-ira-l-escalade-de-la-24-01-2014,45780.html">actes de violence toujours plus fréquents et impunis</a> contre les professionnels des médias, manœuvres d'intimidation contre les journalistes indépendants... Fin 2013, les acquis de la "révolution orange" en matière de liberté de l'information étaient déjà bien entamés.
</p><p>
Au Tadjik</p><p>istan, la couverture de la campagne présidentielle a été nettement déséquilibrée en faveur d’Emomali Rakhmonov, leader omniprésent qui dirige le pays depuis plus de vingt ans. Sur Internet, le <a href="http://fr.rsf.org/tadjikistan-l-un-des-plus-importants-sites-d-25-07-2012,43108.html">blocage arbitraire des sites d’information indépendants s’est banalisé</a>, même s’il ne dure en général que quelques jours. La nouvelle loi sur les médias, entrée en vigueur en mars 2013, comprend sur le papier des éléments satisfaisants, mais elle semble pour l’heure sans effet sur la réalité.
</p>


<?php include "fr-footer.php" ?>