<?php 
	$selected 	= "mo";
	$title 		= "Classement de la liberté de la presse 2014 | AFRIQUE"
?>
<?php include "fr-header.php" ?>

<h2>Afrique du Nord et Moyen-Orient</h2>
<h5>UNE CRISE SYRIENNE LOURDE DE CONSÉQUENCES POUR LA LIBERTÉ DE L’INFORMATION AU MOYEN-ORIENT</h5>
<p>
	La <strong>Syrie</strong> est le <a href="http://fr.rsf.org/syrie-le-journalisme-en-syrie-une-06-11-2013,45422.html">pays le plus dangereux au monde pour les journalistes</a>. L’année 2013 a été marquée par une très forte détérioration de la situation sécuritaire et par la complexification du conflit. Près de cent trente acteurs de l’information ont été tués depuis mars 2011. Ils sont pris en étau : d’un côté, l’armée régulière de Bachar Al-Asad, qui continue à arrêter et à tuer ces témoins gênants qui documentent le conflit ; de l’autre, des groupes islamistes armés dans les zones dites "libérées" du nord du pays, principalement l’Islamic State of Iraq and Sham (ISIS). Depuis le printemps 2013, ces groupes multiplient les enlèvements et mettent en place des comités juridiques (<i>hay’a</i><i>t shar’iya</i>) placés sous le sceau de l’arbitraire. Dans les zones kurdes, les forces de sécurité du PYD (Parti de l’union démocratique), la principale force politique, constituent un obstacle à l’exercice de la liberté de l’information. Menacés de toutes parts, les acteurs syriens de l’information fuient massivement le pays.
</p>	
<div>
<p>
Au <strong>Liban</strong>, où les médias sont des outils de propagande au service d’hommes d’affaires et de politiciens, le conflit syrien consolide la ligne de fracture déjà existante entre, d’un côté, les médias du "8 mars" (mouvement principalement chiite, soutenu par l’Iran et le régime de Damas) et, de l’autre, ceux du "14 mars" (principalement sunnite, soutenu par l’Arabie saoudite, contre le régime de Damas). Cette extrême polarisation entre "médias pro-Damas" et "médias pro-opposition" renforce la polarisation sociopolitique de la société libanaise.
</p><p>
En <strong>Jordanie</strong>, les « printemps arabes » et les événements en Syrie conduisent les autorités à renforcer leur contrôle sur les médias, notamment sur Internet, quitte à susciter un tollé au sein de la société civile jordanienne. En juin 2013, <a href="http://fr.rsf.org/jordanie-rsf-adresse-une-lettre-au-roi-de-18-06-2013,44790.html" target="_blank">près de trois cents sites d’information sont bloqués sur le territoire jordanien</a>, en application d’une nouvelle législation sur la presse qui restreint drastiquement la liberté de l’information en ligne.
</p><p>
L’<strong>Irak</strong> sombre depuis 2012 dans un nouveau cycle de violences, soubresauts de la guerre civile engendrée par l’intervention américaine de 2003 et le chaos dans lequel elle a plongé le pays. Les tensions confessionnelles entre sunnites et chiites sont exacerbées par le conflit syrien et impactent négativement la sécurité des journalistes et l’indépendance des médias, tout comme les entraves quotidiennes de la part des autorités et des forces de sécurité. Ainsi, fin 2013, <a href="http://fr.rsf.org/irak-isis-un-predateur-redoutable-pour-30-12-2013,45679.html" target="_blank">ISIS attaque les locaux de la chaîne de télévision <i>Salaheddine</i></a> à Tikrit (au nord de Bagdad) et tue cinq professionnels de l’information du média.
</p><p>
L’<strong>Iran</strong>, acteur régional incontournable, joue un rôle crucial dans le conflit syrien. Les autorités continuent d’appliquer un contrôle strict de l’information, notamment quand cette dernière touche à son allié de Damas, à la présence des Gardiens de la révolution, aux aides financières. Autant de sujets considérés comme "mettant en danger la sécurité nationale". La question du nucléaire ou la situation des droits de l’homme et des prisonniers d’opinion est également censurée. Fin 2013, l’Iran demeure l’une des plus grandes prisons du monde pour les professionnels des médias avec cinquante journalistes et net-citoyens emprisonnés. Malgré la libération de certains prisonniers d’opinion, les promesses du candidat Hassan Rohani de "libérer tous les prisonniers politiques" et d’un changement "en faveur de la liberté d’expression et de la presse" restent lettre morte depuis son arrivée au pouvoir.
</p>
</div>
<div>
</div>
<div class="encadre">
<p>
<strong>Syrie</strong>
</p><p>
Selon Reporters sans frontières, entre mars 2011 et décembre 2013 :
— près de cent trente acteurs de l’information ont été tués dans le cadre de leurs fonctions dont vingt-cinq journalistes professionnels, dont sept étrangers
</p><p>
— plus de cent-vingt acteurs syriens de l’information ont fui le pays
</p><p>
Fin 2013 :
</p><p>
— près d’une vingtaine d’acteurs syriens de l’information sont détenus par le régime de Bachar al-Asad
</p><p>
— dix-neuf journalistes étrangers sont détenus, retenus en otages ou portés disparus
</p><p>
— plus d’une vingtaine d’acteurs syriens de l’information sont retenus en otages par des groupes armés islamistes
</p>
</div>
<div>
<h5>QUAND DES GROUPES INFRA-ÉTATIQUES SANS LÉGITIMITÉ FONT RÉGNER LA PEUR</h5>
<p>Dans un certain nombre de pays, les groupes infra-étatiques constituent la principale menace pour les acteurs de l’information et sont source d’insécurité. En <strong>Syrie</strong>, des groupes islamistes armés qui multiplient enlèvements et menaces depuis le printemps 2013 sont les nouveaux prédateurs de la liberté de l’information. En <strong>Irak</strong>, les milices armées, souvent rattachées à des organisations politico-confessionnelles, n’hésitent pas à s’en prendre aux journalistes. Fin 2013, ISIS, jusqu’alors actif en Syrie, n’hésite pas à perpétrer des actions contre des médias sur le sol irakien.
</p><p>
En <strong>Libye</strong>, la liberté de l’information est menacée par l’insécurité rampante qui continue d’ébranler le pays. La révolution du 17 février 2011 a entraîné la chute de Muammar Al-Kadhafi après plus de quarante ans d’un pouvoir sans partage s’appuyant sur un contrôle strict de l’information. Trois ans plus tard, être journaliste en Libye demeure une tâche particulièrement ardue. L’élan inspiré par le "printemps des médias" libyens s’essouffle. La Libye "libre", dirigée par un gouvernement de transition, est aujourd’hui caractérisée par un état proche de l’anarchie où le règne des milices armées prévaut sur l’État de droit, et les professionnels des médias en sont profondément affectés : autocensure persistante, menaces à répétition, intimidations, détentions arbitraires, voire torture. Que ce soient des groupes armés sommairement, des structures <i>a</i><i>d hoc </i>légitimées par le gouvernement – comme certains des douze "Boucliers de la Libye", milice placée sous l’autorité du ministère de la Défense libyenne –, ou encore des milices renommées comme Al-Qa’qa’a, tous ont été responsables d’exactions à l’encontre de journalistes.
</p><p>
Les citoyens <strong>yéménites</strong> jouissent d’une plus grande liberté d’expression depuis que ‘Abd Rab Mansour Hadi a succédé à Ali Abdullah Saleh à la présidence en février 2012. Divers groupes armés se rendent pourtant responsables d’une recrudescence des menaces et des violences envers les médias. Qu’ils soient liés à Al-Qaeda dans la péninsule arabique, à la rébellion houthie au Nord, au mouvement sécessionniste au Sud ou à des conservateurs religieux, <a href="http://www.hrw.org/reports/2013/09/19/life-threatening-career">tous s’en prennent aux acteurs de l’information</a>. Les partis politiques jouent également un rôle : les médias yéménites sont pour la plupart affiliés à des organisations politiques dont ils se font les porte-parole. Non contents d’être la cible d’acteurs non étatiques, de nombreux journalistes font face à la méfiance, voire à l’hostilité, des forces de sécurité. L’ONG yéménite <a href="http://www.freedomfoundation-yemen.org/en/">Freedom Foundation</a> – qui assure une veille de la situation des médias dans le pays – recense pour les onze premiers mois de 2013, 268 attaques affectant 356 personnes. Au plus fort du soulèvement en 2011, le Syndicat des journalistes yéménites a recensé trois cent trente-trois attaques contre les journalistes et les médias. Et l’impunité est de mise : la justice a largement échoué à ouvrir des enquêtes sur ces cas d’exactions, tout comme à sanctionner les responsables. Malgré l’ouverture d’un « dialogue national », la loi sur la presse et les publications n’a pas encore été modifiée : tribunaux d’exception et peines privatives de liberté pour les journalistes restent au menu.
</p><p>
<strong>Double peine pour les journalistes irakiens</strong>
</p><p>
</div>
<div class="encadre">
<p>
En <strong>Irak</strong>, des groupes armés n’hésitent pas à s’en prendre aux journalistes. Ainsi, cinq reporters ont été tués à Mossoul en l’espace de trois mois fin 2013. En novembre 2013, deux cameramen, ‘<a href="http://fr.rsf.org/irak-un-quatrieme-journaliste-tue-par-25-11-2013,45507.html" target="_blank">Alaa Edward Boutros</a>, de la chaîne de TV locale <em>Nineveh Al-Ghad</em>, et <a href="http://fr.rsf.org/irak-un-troisieme-journaliste-tue-par-25-10-2013,45377.html" target="_blank">Bachar Abdulqader Najm Al-Nouaïmi</a>, de la chaîne<em> Al-Mosuliya</em>, sont assassinés. Quelques semaines plus tôt, le correspondant de la chaîne <em>Al-Sharqiya TV</em>, <a href="http://fr.rsf.org/irak-le-meurtre-de-deux-journalistes-d-07-10-2013,45291.html">Mohamed Karim Al-Badrani</a>, et son cameraman Mohamed Al-Ghanem, tombaient sous les balles d’inconnus armés. Un mois plus tard, <a href="http://fr.rsf.org/irak-assassinat-d-une-jeune-16-12-2013,45627.html" target="_blank">la jeune présentatrice pour la chaîne <i>Al-Mosuliya</i>, <b>Nawras Al-Nouaimi</b>, est assassinée</a>. L’impunité règne sans partage. Aucun des assassins n’a été arrêté. Au lieu de prendre les mesures nécessaires pour assurer la protection des acteurs de l’information irakiens, les autorités contribuent au climat d’insécurité qui affecte les journalistes en les inculpant pour leurs écrits.
</p>
</div>
<div class="encadre"></div>
<div>
<h5>FRÈRES MUSULMANS ET LIBERTÉ DE L’INFORMATION</h5>
<h6><a href="http://fr.rsf.org/egypte-un-an-apres-l-arrivee-de-mohamed-27-06-2013,44861.html">L’Égypte sous Morsi ou la « frérisation des médias »</a></h6>
<p>
	La chute d’Hosni Moubarak en février 2011 laissait espérer une amélioration de la situation des libertés fondamentales. L’arrivée au pouvoir des Frères musulmans en Égypte à l’été 2012 coupe rapidement court à ces aspirations. En novembre 2012, le président Morsi fait adopter un décret constitutionnel élargissant ses pouvoirs, avant de faire marche arrière à la suite d’une levée de boucliers. La Constitution adoptée fin 2012 par référendum n’apporte pas les garanties suffisantes en matière de liberté d’expression. L’indépendance des médias publics n’est de fait pas assurée. La loi fondamentale ouvre en réalité la voie à une islamisation du cadre légal. Une fois au pouvoir, les Frères musulmans s’attachent à contrôler les médias publics. En août 2012, Mohamed Morsi <a href="http://fr.rsf.org/egypte-detention-preventive-pour-un-23-08-2012,43267.html">fait nommer</a> par la Chambre haute les responsables des titres de la presse gouvernementale proches de la confrérie. Ces nominations influencent largement la ligne éditoriale de ces médias. Les plaintes contre les journalistes ainsi que les agressions explosent.
</p>	
<h6>Une « Sissi-isation » des médias égyptiens à l’œuvre depuis juillet 2013</h6>
<p>Après la prise de pouvoir par l’armée, les nouvelles autorités égyptiennes, dominées par le général Al-Sissi, s’en prennent systématiquement aux médias étrangers ainsi qu’aux médias affiliés aux Frères musulmans, ou considérés comme proches de la confrérie, à nouveau frappée d’interdiction. La chaîne <i>Al-Jazeera</i> est tout particulièrement dans le viseur des autorités. Au cours du second semestre 2013, cinq reporters ont été tués et au moins quatre-vingts journalistes ont été arbitrairement interpellés, par la police ou par des manifestants pro-Morsi ou pro-armée. Les arrestations arbitraires et les tortures se généralisent. La "<a href="http://fr.rsf.org/egypte-rsf-condamne-avec-force-la-29-01-2014,45802.html">chasse aux Frères</a>" vise les journalistes égyptiens, mais aussi leurs confrères turcs, palestiniens ou syriens s’inscrivant en porte-à-faux avec certaines dispositions de la nouvelle Constitution égyptienne, adoptée par référundum en janvier 2014.
</p>
<h6>L’alibi marocain de la lutte contre le terrorisme</h6>
<p>
	Les autorités marocaines, placées sous la houlette des islamistes depuis les élections de 2011, tardent à concrétiser les promesses de réformes annoncées depuis le référendum constitutionnel de 2011. L’année 2013 a été marquée par l’ "<a href="http://fr.rsf.org/maroc-creation-d-un-comite-de-soutien-en-02-10-2013,45274.html" target="_blank">affaire Ali Anouzla</a>". Le directeur de la version arabophone du site d’informations Lakome a été arrêté en septembre pour avoir publié un lien vers un article du quotidien espagnol <i>El Pais</i>, lui-même renvoyant vers une vidéo attribuée au groupe Al-Qaeda au Maghreb islamique (AQMI). Libéré après cinq semaines passées en détention préventive, le journaliste est poursuivi pour "assistance matérielle" et "apologie de crimes terroristes" et encourt de dix à trente ans de réclusion criminelle. Cette affaire illustre l’inquiétant amalgame que font les autorités marocaines entre travail journalistique et incitation à l’exécution d’actes terroristes.
</p>
<div class="encadre">
<h6>En Tunisie : des nominations condamnent l’indépendance des médias publics</h6>
<p>L’accession au pouvoir du parti Ennahda au lendemain des premières élections libres de Tunisie ne permet pas de rompre avec la – traditionnelle – mainmise des autorités sur les médias publics. Reprenant à son compte les habitudes du système Ben Ali, le parti islamiste se lance dans un jeu de chaises musicales, faisant et défaisant les carrières à la tête des radios et télévisions publiques. Le 3 mai 2013, <a href="http://fr.rsf.org/tunisie-la-haica-voit-enfin-le-jour-07-05-2013,44578.html" target="_blank">la nomination des membres de la Haute Autorité indépendante pour la communication audiovisuelle (HAICA)</a> fait renaître les espoirs des défenseurs de la liberté de la presse. Espoirs rapidement déçus par l’annonce inopinée d’une nouvelle vague de nominations aux postes clés de l’audiovisuel public en août de la même année. Trois ans après la chute de Zine el-Abidine Ben Ali, la main de fer du politique continue de courtcircuiter les tentatives de réformes, rendant impossible l’indépendance des médias publics.
</p><p>
</div>
<h5>PÉNINSULE ARABIQUE : LE CONTRÔLE DE L’INFORMATION, UNE PRIORITÉ</h5>
<div>
<p>
Les pays de la péninsule arabique, échaudés par les risques de contagion des « printemps arabes », renforcent leur surveillance et leur contrôle des médias, en commençant par Internet, devenu le lieu d’expression d’une liberté qui ne parvient pas à se faire une place dans les médias traditionnels. Les cyberpolices des monarchies du golfe Persique sont ainsi à l’affût de tout article, billet ou tweet critique, remettant en cause la politique menée.
</p><p>
Aux <strong>Émirats arabes unis</strong>, toute proximité avec les Frères musulmans est réprimée. <a href="http://fr.rsf.org/emirats-arabes-unis-trois-net-citoyens-toujours-08-09-2013,45147.html" target="_blank">Deux net-citoyens</a> qui ont relayé sur Twitter des informations relatives au procès des quatre-vingt-quatorze Émiratis accusés d’affiliation avec le parti Al-Islah ont été condamnés à de lourdes peines de prison. Les autorités avaient décidé <a href="http://fr.rsf.org/emirats-arabes-unis-rsf-condamne-le-black-out-25-03-2013,44255.html" target="_blank">d’interdire l’accès du tribunal aux observateurs et à la presse internationale</a>, laissant des journalistes locaux triés sur le volet couvrir les audiences. Un scénario similaire se profile pour le procès de vingt Égyptiens et dix Émiratis accusés d’entretenir des liens avec les Frères musulmans et d’avoir tenté de renverser le régime. Le 21 janvier 2014, les accusés ont été condamnés à des peines allant de trois mois à cinq ans de prison ferme. Il est fort à parier que Twitter sera examiné à la loupe, et que les autorités n’hésiteront pas à sanctionner lourdement les individus osant braver l’omerta.
</p><p>
L’<strong>Arabie saoudite</strong>, qui figure sur la liste des pays "<a href="http://fr.rsf.org/arabie-saoudite-arabie-saoudite-12-03-2012,42006.html" target="_blank">ennemis d’Internet</a>" de RSF, n’est pas en reste. Le royaume applique une censure implacable à ses propres médias et à Internet, multipliant les condamnations de netcitoyens. En 2013, les censeurs sont particulièrement attentifs aux revendications en faveur du droit pour les femmes à conduire, un sujet très populaire sur le Web et qui bénéficie de certains échos dans les médias traditionnels. Ainsi, fin octobre 2013, <a href="http://fr.rsf.org/arabie-saoudite-un-journaliste-saoudien-arrete-31-10-2013,45406.html" target="_blank">Tariq Al-Moubarak, chroniqueur pour <i>Ash</i><i>a</i><i>r</i><i>q Al-Awsat</i>, a été arrêté </a>pour avoir – entre autres – publié un article dans lequel il critiquait notamment l’interdiction de conduire imposée aux Saoudiennes. Quand il est question de religion, les autorités de Riyad badinent encore moins. Fin juillet 2013, <a href="http://fr.rsf.org/arabie-saoudite-7-ans-de-prison-et-600-coups-de-06-08-2013,45020.html" target="_blank">une condamnation à sept ans de prison ferme et six cents coups de fouet</a> est prononcée en première instance contre le fondateur du site Libéraux saoudiens (censuré depuis). Raef Badawi a publié un article sur la Saint-Valentin dénigrant la police religieuse. Lors de l’ouverture de son procès en juin 2012, il a été initialement poursuivi pour "<a href="https://ifex.org/saudi_arabia/2013/07/31/liberal_blogger/" target="_blank">apostasie</a>" (renoncement à la foi), un chef d’inculpation finalement abandonné.
</p><p>
Au <strong>Koweït</strong>, les autorités opèrent un tour de vis axé sur les deux principaux sujets sensibles : la personne de l’émir et la religion. <a href="http://fr.rsf.org/koweit-un-million-de-dollars-d-amende-10-04-2013,44362.html" target="_blank">Deux citoyens-journalistes</a>, Badr Al-Rashidi et Ourance Al-Rashidi, sont condamnés pour "insulte à l’émir". Leur grâce, en juillet 2013, reste le fait du prince. Sans réforme de la loi, de telles condamnations peuvent encore tomber. En avril 2013, un projet de loi liberticide est abandonné. Il prévoyait des amendes pouvant aller jusqu’à près de 800 000 euros pour « critique envers l’émir ou le prince héritier » et des peines pouvant aller jusqu’à dix ans d’emprisonnement pour « offense à Dieu, aux prophètes de l’islam, ou encore aux compagnons ou épouses du prophète Mahomet ».
</p><p>
À <strong>Oman</strong>, enfin, la personne du sultan reste l’un des principaux tabous. Quiconque le critique <a href="http://fr.rsf.org/oman-le-sultan-qaboos-gracie-l-ensemble-22-03-2013,44250.html">s’expose aux foudres du pouvoir</a>. Certains l’ont payé cher avant d’être parfois graciés.
</p>
</div>
<div class="encadre">
<h6>Le Bahreïn, royaume de la désinformation</h6>
<p>
Depuis le début du soulèvement populaire en février 2011, les autorités bahreïnies sont passées maîtresses dans l’art de <a href="http://fr.rsf.org/bahrein-don-t-leave-news-out-of-the-race-18-04-2013,44387.html">manipuler l’information sur les manifestations et leur répression</a>. Soucieuses de leur image, elles ont su manier habilement des puissances occidentales réticentes à condamner les exactions qui y ont été commises, sachant se contenter des effets d’annonce des dirigeants bahreïnis et de réformes superficielles. Ainsi, Manama a été désignée capitale de la culture arabe en 2012, puis capitale du tourisme arabe en 2013. Dernier coup de maître de ces as de la communication : le Bahreïn accueillera la <a href="http://fr.rsf.org/bahrein-http-fr-rsf-org-bahrein-cinq-acteurs-de-l-information-03-09-2013-45133-03-09-2013,45133.html">Cour arabe des droits de l’homme de la Ligue arabe</a>… en dépit du fait que certaines prisons du royaume regorgent de prisonniers de conscience.
</p>
</div>
</div>

<?php include "fr-footer.php" ?>