<?php 
	$selected 	= "ue";
	$title 		= "Classement de la liberté de la presse 2014 | AFRIQUE"
?>
<?php include "fr-header.php" ?>
<h2>Union européenne et Balkans</h2>
<h5>UNION EUROPÉENNE : DES DROITS FONDAMENTAUX GARANTIS MAIS MENACÉS</h5>
<div>
<p>
C’est un Conseil de l’Europe âgé d’un an à peine qui affirme, en 1950, la « liberté de recevoir ou de communiquer des informations ou des idées sans qu’il puisse y avoir ingérence d’autorités publiques et sans considération de frontières ». Soixante-trois ans plus tard, cette affirmation a été réitérée à de nombreuses reprises dans plusieurs textes ayant scellé les fondements de l’Union européenne. En conséquence, des garanties du droit européen de qualité et explicites s’imposent aux États membres : la Convention de sauvegarde des droits de l’homme et des libertés fondamentales, entrée en vigueur en 1953, et la Charte des droits fondamentaux de l’Union européenne, proclamée en 2000, consacrent la liberté d’informer et d’être informé. La réalité pourrait paraître en adéquation avec les textes : le Vieux Continent domine largement le classement mondial de la liberté de la presse, avec trente et un représentants sur les cinquante pays les mieux classés. Les modèles en termes de liberté de la presse sont au Nord, en Finlande, en Norvège, ou aux Pays-Bas, pays qui occupent la tête du classement depuis de nombreuses années. Leur succès repose sur des fondements constitutionnels et légaux solides, qui s’appuient sur une véritable culture des libertés individuelles, davantage intégrée qu’au Sud.
</p><p>
Seule évolution positive dans cette partie de l’Union, l’Italie, qui sort enfin d’une spirale négative alors qu’une loi encourageante dépénalisant la diffamation par voie de presse est en préparation.</div>
</p><p>
Le premier pays du classement depuis 2008, la Finlande, présente paradoxalement deux handicaps à l’épanouissement d’un environnement serein pour la liberté de l’information : les peines de prison pour diffamation existent bien, et l’ensemble des médias nationaux sont entre les mains de trois principaux propriétaires. Il est pourtant extrêmement rare que de telles peines soient prononcées contre des journalistes pour leurs écrits, et un pluralisme très riche a pu se développer malgré cette structure financière très concentrée. Dans ce pays où le papier résiste bien au numérique, la presse est autorégulée par l’intermédiaire du Council for Mass Media, corps indépendant reposant sur l’adhésion volontaire des titres de presse et des associations de journalistes, et dont le financement est majoritairement assuré par les cotisations de ses membres.
</p><p>
Malgré les bonnes performances de l’Union européenne au classement mondial de la liberté de la presse, des faits regrettables entachent l’action de certains États membres en matière de protection de la liberté de l’information. Parmi eux, le Royaume-Uni et la France, pays traditionnellement respectueux de la liberté de la presse, mais qui ont connu une année 2013 inquiétante.
</p><p>
Le couple franco-allemand connaît des turbulences. L’Allemagne se maintient en bonne position mais la France décroche légèrement. Alors que le Conseil constitutionnel français a entériné <a href="http://fr.rsf.org/france-loi-sur-la-transparence-rsf-17-09-2013,45187.html">une loi rendant passible de prison la publication des patrimoines de certains élus</a>, l’Hexagone, qui est toujours dans l’attente d’une loi efficace de protection du secret des sources, accuse un recul d’une place. Point d’orgue de l’année 2013, <a href="https://www.wefightcensorship.org/fr/censored/affaire-bettencourt-justice-censure-enregistrementshtml.html">la décision prise par la justice française de faire retirer les enregistrements de l’affaire Bettencourt des publications de Mediapart et du <i>Point </i></a>: une atteinte grave à liberté de la presse, violant le droit du public à être informé d’une affaire d’intérêt général impliquant des responsables politiques de premier plan.
</p><p>
Au Royaume-Uni, le gouvernement britannique a dépêché des agents dans les sous-sols du <i>Gua</i><i>r</i><i>di</i><i>a</i><i>n</i>, <a href="http://fr.rsf.org/royaume-uni-l-acharnement-coupable-du-20-08-2013,45072.html">pour y faire détruire les disques durs du quotidien contenant des informations pointant les pratiques des services de renseignement britanniques (GCHQ)</a>. Peu de temps après, le conjoint de Glenn Greenwald, l’ex-blogueur vedette du quotidien ayant collaboré avec le lanceur d’alerte Edward Snowden, a été détenu pendant neuf heures à l’aéroport d’Heathrow sous le régime du <i>T</i><i>e</i><i>rrorism Act</i>. En mélangeant journalisme et terrorisme, les autorités britanniques reproduisent de manière inquiétante et surtout avec une facilité déconcertante l’une des pratiques les plus répandues des régimes autoritaires. Dans un tel contexte, la société civile ne pouvait que s’inquiéter d’une charte royale visant à réguler la presse. Adoptée à la suite du scandale des écoutes téléphoniques menées par le tabloïd <i>New</i><i>s of the World</i>, son impact sur la liberté de l’information au Royaume-Uni sera mesuré dans la prochaine édition du classement mondial.
</p><p>
Ces éléments montrent que si la liberté de l’information bénéficie d’un encadrement légal de qualité et s’exerce de manière relativement satisfaisante à l’échelle de l’Union européenne, elle reste soumise à rude épreuve dans certains pays membres, y compris chez ceux se réclamant le plus des libertés individuelles.
</p>
<h6>La Bulgarie, dernier pays de la zone UE</h6>
<div class="encadre">
<p>
Au coude à coude avec la Grèce pour la dernière place des pays de l’Union européenne, c’est bien la Bulgarie qui conservera ce triste privilège au terme d’une année difficile, marquée par cinq mois de manifestations et un climat politique tendu. En marge de ces manifestations massives demandant la démission du gouvernement, <a href="http://fr.rsf.org/bulgarie-manifestations-a-sofia-des-26-07-2013,44979.html">des journalistes seront victimes d’agressions répétées par les forces de l’ordre</a>. Sur un autre terrain, la situation est aussi tendue pour les journalistes indépendants, notamment pour les journalistes d’investigation, dont les voitures partent parfois en fumée. Ainsi en 2013, la journaliste Genka Shikerova, réputée pour ses interviews politiques sans concessions, <a href="http://fr.rsf.org/bulgarie-liberte-de-l-information-en-02-10-2013,45270.html">a vu son véhicule incendié devant chez elle à Sofia</a>. L’année 2012 avait été marquée par l’incendie de la voiture de la journaliste d’investigation Lidia Pavlova.
</p>
</div>
<h5>DES PAYS EUROPÉENS À LA DÉRIVE SOMBRENT DANS LE CLASSEMENT</h5>
<div>
<p>
Si la liberté de l’information est parfois malmenée dans certains pays de l’Union européenne, elle est très clairement bafouée dans d’autres. C’est le cas de la Grèce, qui a perdu plus de cinquante places au classement mondial de la liberté de la presse en l’espace deseulement cinq ans. Une chute vertigineuse pour la plus vieille démocratie du monde. La crise économique de 2007 affecte tout particulièrement le secteur médiatique grec. Les quelques riches armateurs et entrepreneurs qui financent les médias nationaux réorientent leurs investissements vers des activités économiques plus rentables. Les plans de licenciements se succèdent, le chômage frappant durement les journalistes. Outre les difficultés économiques, la presse grecque traîne une réputation plombée par des années de clientélisme. Alors que les manifestations s’enchaînent pour protester contre les mesures d’austérité dictées par des gouvernements éphémères, les journalistes couvrent tant bien que mal les événements, pris en étau entre des policiers souvent violents et des manifestants qui les accusent de collusion avec le pouvoir.
</p><p>
La situation sécuritaire s’aggrave avec la montée en puissance du parti néonazi Aube dorée, qui compte en juin 2012 près de vingt sièges au Voulí, le Parlement, à la faveur d’un euroscepticisme et d’une hostilité croissants envers les étrangers accusés de « voler la Grèce ». Les cadres d’Aube dorée, suivis par leurs militants, ciblent ouvertement les journalistes. <a href="http://fr.rsf.org/grece-aube-doree-sur-le-point-d-acceder-04-06-2013,44705.html">Les agressions deviennent systématiques dans tout le pays et les menaces de mort se multiplient</a>.
</p><p>
En juin 2013, la Grèce connaît un tournant important de son histoire médiatique. Engagé dans une course à la réduction des coûts, le gouvernement du conservateur Antonis Samaras prend une décision sans précédent pour un pays membre de l’Union européenne : sous la pression de la troïka (Commission européenne, Banque centrale, FMI) qui réclame des coupes budgétaires, <a href="http://fr.rsf.org/grece-le-secretaire-general-de-rsf-se-12-06-2013,44768.html">le Premier ministre décide de fermer le groupe d’audiovisuel public grec (ERT)</a>, et avec lui ses quatre chaînes de télévision et ses cinq radios. Alors qu’en quelques heures seulement la décision est signifiée au groupe ERT, les écrans noirs indiquant « No signal » plongent l’Europe et le monde dans la consternation. Sous la pression internationale, le gouvernement annonce la création d’un nouveau groupe d’audiovisuel public : NERIT.
</p><p>
Au coude à coude avec la Grèce dans le classement mondial de Reporters sans frontières, la Hongrie est confrontée, depuis l’accession au pouvoir de Viktor Orbán en 2010, à une érosion continue des libertés publiques, au premier rang desquelles celle de l’information. Le gouvernement Orbán, qui dispose d’une majorité des deux tiers au sein du Parlement, a fait adopter en 2011 une loi sur les médias hautement restrictive. Introduisant des amendes pour les auteurs de contenus ne respectant pas les critères d’une « information équilibrée », notion intentionnellement floue, le texte prévoyait aussi la création d’une dangereuse autorité de régulation des médias. Statutairement lié au parti majoritaire, le Fidesz-MPSz (parti conservateur), le « Conseil des médias » n’apportait qu’une seule garantie : celle d’une ingérence politique dans les contenus d’information. L’Union européenne est depuis parvenue à faire revenir le gouvernement hongrois sur certaines dispositions, mais pas à ajourner les plus liberticides.</div>
Dans cette chasse à l’information indépendante, la station Klubradio devient à elle seule le symbole de la lutte pour le droit à être informé. Le nouveau Conseil des médias refuse de renouveler la licence de la radio, malgré son ancienneté et ses centaines de milliers d’auditeurs, pour attribuer sa fréquence à une station inconnue du public. Face à la mobilisation populaire, et après plusieurs décisions de justice, l’autorité de régulation finit par accorder à Klubradio une licence à long terme en mars 2013.
</p>
<div class="encadre">
<h6>28e membre de l’UE, la Croatie fait face à des défis</h6>
<p>Le 1er juillet 2013, la Croatie est devenue le vingt-huitième pays membre de l’Union européenne. Six années de négociations avec la Commission européenne ont conduit le pays à opérer des transformations importantes, parmi lesquelles l’inscription, en 2010, dans la Constitution de la liberté des médias et du droit à accéder à l’information. De nombreux progrès restent à faire. La société de radiotélévision croate (HRT), groupe d’audiovisuel public, est pointée pour son manque d’indépendance après les réformes menées par le gouvernement de Zoran Milanović (centre gauche). Depuis juillet 2012, les nominations du directeur du HRT, des membres de son comité de surveillance et de ses administrateurs sont confiées au Parlement : cette disposition instaure un contrôle politique des contenus par le parti majoritaire.
</p>
</div>
<h5>LES BALKANS : UNE POUDRIÈRE POUR LES JOURNALISTES</h5>
<div>
<p>
La Macédoine brigue l’intégration à l’Union européenne depuis 2005. Après huit ans, les négociations en ce sens n’ont toujours pas débuté. Empêtré dans le « conflit du nom », qui l’oppose à la Grèce depuis son indépendance en 1991 et entrave les pourparlers – le nom de la Macédoine étant revendiqué par les deux États et les deux peuples –, le pays mène malgré tout des réformes pour mettre le pays sur la voie de l’adhésion. Le vernis démocratique utilisé par le gouvernement macédonien depuis quelques années ne fait pourtant que cacher la multiplication des atteintes à la liberté de l’information.
</p><p>
Tomislav Kezarovski est devenu le symbole de cette dérive. <a href="http://fr.rsf.org/macedoine-le-journaliste-tomislav-kezarovski-21-10-2013,45352.html">Condamné à quatre ans et demi de prison en octobre 2013</a> pour avoir révélé l’identité d’un témoin protégé dans une affaire de meurtre, le journaliste a, sous la pression internationale, vu sa peine transformée en assignation à résidence. Le lendemain de sa sortie de prison, l’un de ses confrères et compatriotes est arrêté en Serbie sur mandat d’Interpol pour « espionnage ». Il s’agit de Zoran Bozinovski, connu dans les Balkans comme le « Julian Assange macédonien ». Il s’est notamment illustré pour ses enquêtes sur Sashe Mijalko, chef des services secrets et membre de la famille du Premier ministre Nikola Gruevski.
</p><p>
Au Monténégro, la sécurité des journalistes demeure une préoccupation majeure. Le plus jeune pays d’Europe, indépendant de la Serbie depuis 2006, peut compter sur un journalisme d’investigation plus développé que chez certains de ses voisins. Les quotidiens <i>Vijest</i><i>i </i>et <i>D</i><i>a</i><i>n </i>ainsi que le magazine <i>Mon</i><i>i</i><i>to</i><i>r </i>portent cette information libre, mais leurs journalistes doivent régulièrement faire face à des intimidations et à des agressions physiques. D’une extrême gravité, pour certaines.
</p><p>
En août 2013, <a href="http://fr.rsf.org/montenegro-attaque-a-la-bombe-contre-le-13-08-2013,45046.html">une charge de TNT explose devant le domicile de Tufik Softić</a>, journaliste d’investigation et collaborateur de <i>V</i><i>i</i><i>jest</i><i>i </i>et <i>Monitor</i>. Coutumière des menaces et des agressions, la victime n’est heureusement pas touchée par l’explosion qui aurait pu, à quelques minutes près, se révéler meurtrière. Enquêtant depuis plusieurs années sur les organisations clandestines et le trafic de drogue, Tufik Softić avait aussi mis en cause des responsables politiques dans ses articles. La réponse des autorités à ces violences est malheureusement bien en deçà des attentes. Pour preuve de cette impunité, le commanditaire de l’assassinat de Dusko Jovanović, rédacteur en chef du quotidien <i>D</i><i>a</i><i>n </i>abattu en pleine rue en 2004, n’a jamais été retrouvé ni condamné.
</p><p>
La menace n’est pas que physique. D’autres moyens sont employés pour tenter de faire taire les journalistes indépendants. Le Monténégro, à l’instar de la Macédoine, vise depuis 2010 l’entrée au sein de l’UE. La classe politique du pays maîtrise parfaitement le langage des institutions européennes. Elle maintient à l’intention de la communauté internationale l’illusion d’une ambition démocratique, une communauté internationale plus préoccupée par la stabilité de la région que par les progrès en matière de libertés. Au pouvoir depuis près de vingt ans, le Parti démocratique socialiste du Monténégro (DPS) de l’incontournable et très riche président du pays Milo Djukanović, ancien proche de Slobodan Milošević et homme d’affaires controversé, mène de véritables campagnes de haine contre les journalistes indépendants. Régulièrement qualifiés de « traîtres à la nation » ou de « fascistes », ces derniers essuient aussi des insultes et des menaces d’une incroyable vulgarité. En 2013, peu après la publication d’une tribune titrée « Danse avec le dictateur », la directrice de <i>Monito</i><i>r</i>, Milka Tadić-Mijović, a fait l’objet de vindictes sexistes ordurières, notamment par SMS. Malgré une plainte auprès de la police, qui dispose du numéro de téléphone ayant émis ce SMS, aucune poursuite n’a été engagée.</div>
</p>
<div class="encadre">
<h6></h6>
<h6>L’Albanie ouvre une nouvelle page de son histoire médiatique</h6>
<p>Les élections albanaises du 23 juin 2013 marquent une alternance politique. Le Parti socialiste albanais arrive au pouvoir après des élections incontestables qui tranchent avec les exercices électoraux compliqués des vingt dernières années en Albanie. Son programme pour le paysage médiatique albanais est ambitieux : définir une nouvelle législation qui améliore la transparence de la propriété des médias, renforcer l’indépendance du groupe d’audiovisuel public et garantir l’accès à l’information des institutions albanaises aux médias. En octobre 2013, les onze membres du conseil d’administration du groupe d’audiovisuel public avaient dépassé leur mandat d’un an. Une donnée qui laisse entrevoir l’ampleur de la tâche du nouveau gouvernement, dont l’objectif est d’obtenir le statut de candidat à l’adhésion à l’Union européenne.</div>
</p>
<?php include "fr-footer.php" ?>